#!/usr/bin/env python3
"""Generate GLADIUS known-truth validation artifacts.

GLADIUS is evaluated on a paper-side high-dimensional-state known-truth DGP.
The artifact is deliberately strict: policy fit is not enough for a structural
counterfactual claim unless projected reward, raw Bellman reward, value, Q, and
Type A/B/C counterfactual regret gates pass too.
"""

from __future__ import annotations

import argparse
import math
import sys
from dataclasses import replace
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
JSON_OUT = ROOT / "validation" / "results" / "gladius.json"
DEFAULT_OUTPUT_DIR = Path("/tmp/econirl_gladius_known_truth")
DEFAULT_CELL_ID = "gladius_paper_high_state"
ESTIMATOR = "GLADIUS"

for path in (HERE.parent, ROOT, ROOT / "src"):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from validation_display import (  # noqa: E402
    validation_context,
    validation_display_name,
)
from validation.known_truth import (  # noqa: E402
    RecoveryGateFailure,
    build_known_truth_dgp,
    get_cell,
    run_estimator,
    simulate_known_truth_panel,
    stable_hash,
    write_json,
)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cell-id", default=DEFAULT_CELL_ID)
    parser.add_argument("--n-individuals", type=int, default=None)
    parser.add_argument("--n-periods", type=int, default=None)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--json-out", type=Path, default=JSON_OUT)
    parser.add_argument("--show-progress", action="store_true", default=False)
    parser.add_argument("--quiet-progress", action="store_false", dest="show_progress")
    parser.add_argument("--verbose", action="store_true")
    parser.add_argument("--enforce-gates", action="store_true")
    args = parser.parse_args()

    print("GLADIUS primer: running known-truth validation")
    print(f"  cell: {args.cell_id}")
    print(f"  estimator: {ESTIMATOR}")
    print(f"  output_dir: {args.output_dir}")

    record = run_validation_cell(args)
    write_json(args.json_out, compact_payload(record))

    payload = record["payload"]
    failed = [gate for gate in payload["gates"] if not gate.passed]
    print(f"  result: {record['run_dir'] / 'result.json'}")
    print(
        "  strict structural gates: "
        f"{len(payload['gates']) - len(failed)} pass, {len(failed)} fail"
    )
    print(f"  wrote: {args.json_out}")
    print(f"  wrote: {args.tex_out}")

    if args.enforce_gates and failed:
        raise RecoveryGateFailure(
            "; ".join(
                f"{gate.name}={gate.value} {gate.operator} {gate.threshold}"
                for gate in failed
            )
        )


def run_validation_cell(args: argparse.Namespace) -> dict[str, Any]:
    cell = get_cell(args.cell_id)
    dgp = build_known_truth_dgp(cell.dgp_config)
    simulation_config = replace(
        cell.simulation_config,
        n_individuals=(
            cell.simulation_config.n_individuals
            if args.n_individuals is None else args.n_individuals
        ),
        n_periods=(
            cell.simulation_config.n_periods
            if args.n_periods is None else args.n_periods
        ),
        show_progress=args.show_progress,
    )
    panel = simulate_known_truth_panel(dgp, simulation_config)
    main_run = run_estimator(
        ESTIMATOR,
        dgp,
        panel,
        smoke=False,
        verbose=args.verbose,
        enforce_gates=False,
    )
    payload = {
        "cell": cell,
        "simulation": simulation_config,
        "estimator": ESTIMATOR,
        "diagnostics": main_run.diagnostics,
        "compatibility": main_run.compatibility,
        "summary": main_run.summary,
        "metrics": main_run.metrics,
        "gates": main_run.gates,
    }
    run_hash = stable_hash(
        {
            "cell": cell.dgp_config.to_dict(),
            "simulation": simulation_config,
            "estimator": ESTIMATOR,
            "primer": "gladius",
        }
    )
    run_dir = args.output_dir / f"{cell.cell_id}_gladius_{run_hash}"
    write_json(run_dir / "result.json", payload)
    return {"payload": payload, "dgp": dgp, "run_dir": run_dir}


def render_results_tex(record: dict[str, Any]) -> str:
    payload = record["payload"]
    dgp = record["dgp"]
    cell = payload["cell"]
    sim = payload["simulation"]
    metrics = payload["metrics"]
    gates = payload["gates"]
    failed = [gate for gate in gates if not gate.passed]
    passed = len(gates) - len(failed)
    cf = metrics["counterfactuals"]

    lines: list[str] = []
    add = lines.append
    add("% Auto-generated by gladius_results.py. Do not edit by hand.")
    add(f"% Known-truth DGP cell: {cell.cell_id}")
    add("")
    display = validation_display_name(cell.cell_id)
    add(r"\subsection{Known-Truth Validation Results: " + tex_text(display) + "}")
    add(
        "GLADIUS is evaluated on a paper-side high-dimensional-state, "
        "low-dimensional-reward DGP with an exit-action reward anchor and the "
        "stable anchor-moment Q loss. The gate set is structural: convergence, "
        "final loss, parameter recovery, raw Bellman reward recovery, "
        "projected reward recovery, policy distance, value/Q recovery, and "
        "Type A/B/C counterfactual regret."
    )
    add("")
    add(r"\subsection{Validation Design Context}")
    add(validation_context([cell.cell_id]))
    add("")
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{GLADIUS paper-side high-dimensional-state known-truth cell.}")
    add(r"\begin{tabular}{lrrrrrr}")
    add(r"\toprule")
    add(
        r"Cell & States & State features & Actions & Reward features & "
        r"Individuals & Periods \\"
    )
    add(r"\midrule")
    add(
        f"{tex_text(display)} & {dgp.problem.num_states} & "
        f"{dgp.state_features.shape[-1]} & {dgp.problem.num_actions} & "
        f"{dgp.feature_matrix.shape[-1]} & "
        f"{sim.n_individuals:,} & {sim.n_periods} \\\\"
    )
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{GLADIUS strict structural validation. Lower is better.}")
    add(r"\resizebox{\textwidth}{!}{%")
    add(r"\begin{tabular}{lrrrrrrrrr}")
    add(r"\toprule")
    add(
        r"Gates & Param cos. & Param rRMSE & Policy TV & Raw reward nRMSE & "
        r"Proj. reward nRMSE & Value nRMSE & Q nRMSE & Type A/B/C regret \\"
    )
    add(r"\midrule")
    add(
        f"{passed}/{len(gates)} & "
        f"{fmt(metrics['parameters'].cosine_similarity, 4)} & "
        f"{fmt(metrics['parameters'].relative_rmse, 4)} & "
        f"{fmt(metrics['policy'].tv, 4)} & "
        f"{fmt(metrics.get('raw_bellman_reward_normalized_rmse'), 4)} & "
        f"{fmt(metrics.get('projected_reward_normalized_rmse'), 4)} & "
        f"{fmt(metrics.get('value_normalized_rmse'), 4)} & "
        f"{fmt(metrics.get('q_normalized_rmse'), 4)} & "
        f"{fmt(cf['type_a'].regret, 4)}/{fmt(cf['type_b'].regret, 4)}/"
        f"{fmt(cf['type_c'].regret, 4)} \\\\"
    )
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"}")
    add(r"\end{table}")
    add("")
    if failed:
        add(
            f"GLADIUS passes {passed}/{len(gates)} strict structural gates and "
            "is not treated as counterfactual-valid on this DGP."
        )
    else:
        add(
            f"GLADIUS passes {len(gates)}/{len(gates)} strict structural gates "
            "and is treated as counterfactual-valid on this DGP."
        )
    add("")
    return "\n".join(lines)


def compact_payload(record: dict[str, Any]) -> dict[str, Any]:
    payload = record["payload"]
    summary = payload["summary"]
    metadata = summary.metadata
    metrics = payload["metrics"]
    gates = payload["gates"]
    failed = [gate.name for gate in gates if not gate.passed]
    return {
        "estimator": ESTIMATOR,
        "primary_cell_id": payload["cell"].cell_id,
        "status": (
            "strict_structural_counterfactual_pass"
            if not failed
            else "strict_structural_counterfactual_fail"
        ),
        "counterfactual_valid_certified": not failed,
        "failed_gates": failed,
        "simulation": payload["simulation"],
        "compatibility": payload["compatibility"],
        "diagnostics": payload["diagnostics"],
        "summary": {
            "converged": summary.converged,
            "num_iterations": summary.num_iterations,
            "num_observations": summary.num_observations,
            "estimation_time": summary.estimation_time,
            "log_likelihood": summary.log_likelihood,
            "metadata": {
                "final_loss": metadata.get("final_loss"),
                "anchor_action": metadata.get("anchor_action"),
                "anchor_bellman_loss": metadata.get("anchor_bellman_loss"),
                "anchor_bellman_mode": metadata.get("anchor_bellman_mode"),
            },
        },
        "metric_groups": {
            "imitation_policy": {
                "policy_tv": metrics["policy"].tv,
                "policy_kl": metrics["policy"].kl,
            },
            "projected_structural_parameters": {
                "parameter_cosine": metrics["parameters"].cosine_similarity,
                "parameter_relative_rmse": metrics["parameters"].relative_rmse,
            },
            "reward_table_recovery": {
                "raw_bellman_reward_normalized_rmse": metrics.get(
                    "raw_bellman_reward_normalized_rmse"
                ),
                "projected_reward_normalized_rmse": metrics.get(
                    "projected_reward_normalized_rmse"
                ),
            },
            "value_q_recovery": {
                "value_normalized_rmse": metrics.get("value_normalized_rmse"),
                "q_normalized_rmse": metrics.get("q_normalized_rmse"),
            },
            "counterfactual_recovery": {
                kind: cf.regret
                for kind, cf in metrics["counterfactuals"].items()
            },
        },
        "metrics": metrics,
        "gates": gates,
    }


def fmt(value: float | None, digits: int = 4) -> str:
    if value is None:
        return "---"
    number = float(value)
    if not math.isfinite(number):
        return "---"
    return f"{number:.{digits}f}"


def tex_text(value: str) -> str:
    return (
        str(value)
        .replace("\\", r"\textbackslash{}")
        .replace("_", r"\_")
        .replace("%", r"\%")
        .replace("&", r"\&")
        .replace("#", r"\#")
    )


if __name__ == "__main__":
    main()
