#!/usr/bin/env python3
"""NFXP-NK Primer — auto-generate results for the LaTeX document.

Runs NFXP on the Rust bus engine (90 states, beta=0.95) and compares
against Behavioral Cloning. NFXP's steelman: exact MLE with analytical
standard errors and 100% policy recovery on the canonical DDC problem.

Usage:
    cd /path/to/econirl
    .venv/bin/python papers/econirl_package/primers/nfxp/nfxp_run.py
"""

import json
import time
from pathlib import Path

import jax.numpy as jnp
import numpy as np

OUT = Path(__file__).resolve().parent / "nfxp_results.tex"

TRUE_OC = 0.001
TRUE_RC = 3.0
N_BINS = 90
BETA = 0.95
N_INDIVIDUALS = 500
N_PERIODS = 100
SEED = 42


def main():
    from econirl.environments.rust_bus import RustBusEnvironment
    from econirl.estimation.nfxp import NFXPEstimator
    from econirl.estimation.behavioral_cloning import BehavioralCloningEstimator
    from econirl.preferences.linear import LinearUtility
    from econirl.simulation.synthetic import simulate_panel
    from econirl.core.bellman import SoftBellmanOperator
    from econirl.core.solvers import policy_iteration

    n_obs = N_INDIVIDUALS * N_PERIODS
    print(f"NFXP Primer — generating results")
    print(f"  Rust bus: {N_BINS} states, beta={BETA}, {n_obs:,} obs")

    env = RustBusEnvironment(
        operating_cost=TRUE_OC,
        replacement_cost=TRUE_RC,
        num_mileage_bins=N_BINS,
        discount_factor=BETA,
    )
    utility = LinearUtility.from_environment(env)
    problem = env.problem_spec
    transitions = env.transition_matrices

    panel = simulate_panel(env, n_individuals=N_INDIVIDUALS,
                           n_periods=N_PERIODS, seed=SEED)

    # True policy for accuracy comparison
    operator = SoftBellmanOperator(
        problem, jnp.asarray(transitions, dtype=jnp.float64)
    )
    true_params = jnp.array([TRUE_OC, TRUE_RC])
    true_reward = jnp.asarray(
        utility.compute(jnp.asarray(true_params, dtype=jnp.float32)),
        dtype=jnp.float64,
    )
    true_result = policy_iteration(
        operator, true_reward, tol=1e-10, max_iter=200, eval_method="matrix"
    )
    true_policy = np.array(true_result.policy)
    true_actions = np.argmax(true_policy, axis=1)

    results = {}

    # ── BC baseline ──
    print("\n  Running BC...")
    t0 = time.time()
    bc = BehavioralCloningEstimator(smoothing=1.0, verbose=False)
    bc_res = bc.estimate(panel, utility, problem, jnp.asarray(transitions))
    bc_time = time.time() - t0
    bc_policy = np.array(bc_res.policy)
    bc_actions = np.argmax(bc_policy, axis=1)
    bc_acc = float(np.mean(bc_actions == true_actions))
    results["bc"] = {
        "ll": float(bc_res.log_likelihood),
        "policy_acc": bc_acc,
        "time": bc_time,
    }
    print(f"    LL={results['bc']['ll']:.2f}, policy_acc={bc_acc:.2%}, time={bc_time:.2f}s")

    # ── NFXP ──
    print("\n  Running NFXP-NK...")
    t0 = time.time()
    nfxp = NFXPEstimator(se_method="robust", verbose=False)
    nr = nfxp.estimate(panel, utility, problem, transitions)
    nfxp_time = time.time() - t0
    est_params = np.array(nr.parameters)
    est_se = np.array(nr.standard_errors)
    est_policy = np.array(nr.policy)
    est_actions = np.argmax(est_policy, axis=1)
    nfxp_acc = float(np.mean(est_actions == true_actions))
    results["nfxp"] = {
        "oc": float(est_params[0]),
        "rc": float(est_params[1]),
        "se_oc": float(est_se[0]),
        "se_rc": float(est_se[1]),
        "ll": float(nr.log_likelihood),
        "policy_acc": nfxp_acc,
        "time": nfxp_time,
        "converged": bool(nr.converged),
    }
    print(f"    OC={est_params[0]:.6f} (SE={est_se[0]:.6f}), RC={est_params[1]:.4f} (SE={est_se[1]:.4f})")
    print(f"    LL={nr.log_likelihood:.2f}, policy_acc={nfxp_acc:.2%}, time={nfxp_time:.2f}s")

    # ── Write LaTeX ──
    def fmt(v, d=4):
        return f"{v:.{d}f}"

    tex = []
    tex.append("% Auto-generated by nfxp_run.py — do not edit by hand")
    tex.append(f"% Rust bus, {N_BINS} states, beta={BETA}, {n_obs:,} obs")
    tex.append("")

    # Macros
    tex.append(f"\\newcommand{{\\nfxpNstates}}{{{N_BINS}}}")
    tex.append(f"\\newcommand{{\\nfxpBeta}}{{{BETA}}}")
    tex.append(f"\\newcommand{{\\nfxpNobs}}{{{n_obs:,}}}")
    tex.append(f"\\newcommand{{\\nfxpTrueOC}}{{{TRUE_OC}}}")
    tex.append(f"\\newcommand{{\\nfxpTrueRC}}{{{TRUE_RC}}}")
    tex.append("")
    tex.append(f"\\newcommand{{\\nfxpOC}}{{{fmt(results['nfxp']['oc'], 6)}}}")
    tex.append(f"\\newcommand{{\\nfxpRC}}{{{fmt(results['nfxp']['rc'])}}}")
    tex.append(f"\\newcommand{{\\nfxpSEoc}}{{{fmt(results['nfxp']['se_oc'], 6)}}}")
    tex.append(f"\\newcommand{{\\nfxpSErc}}{{{fmt(results['nfxp']['se_rc'])}}}")
    tex.append(f"\\newcommand{{\\nfxpLL}}{{{fmt(results['nfxp']['ll'], 2)}}}")
    tex.append(f"\\newcommand{{\\nfxpAcc}}{{{fmt(results['nfxp']['policy_acc'] * 100, 1)}\\%}}")
    tex.append(f"\\newcommand{{\\nfxpTime}}{{{fmt(results['nfxp']['time'], 2)}}}")
    tex.append("")
    tex.append(f"\\newcommand{{\\bcLL}}{{{fmt(results['bc']['ll'], 2)}}}")
    tex.append(f"\\newcommand{{\\bcAcc}}{{{fmt(results['bc']['policy_acc'] * 100, 1)}\\%}}")
    tex.append(f"\\newcommand{{\\bcTime}}{{{fmt(results['bc']['time'], 2)}}}")
    tex.append("")

    # Table
    tex.append("\\begin{table}[H]")
    tex.append("\\centering\\small")
    tex.append(f"\\caption{{Rust bus engine (\\nfxpNstates\\ states, "
               f"$\\beta = \\nfxpBeta$, \\nfxpNobs\\ obs). "
               f"True parameters: $\\theta_c = \\nfxpTrueOC$, $RC = \\nfxpTrueRC$.}}")
    tex.append("\\label{tab:nfxp_results}")
    tex.append("\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}} l r r}")
    tex.append("\\toprule")
    tex.append("Metric & BC & NFXP-NK \\\\")
    tex.append("\\midrule")
    tex.append("$\\hat\\theta_c$ & --- & \\nfxpOC\\ (\\nfxpSEoc) \\\\")
    tex.append("$\\widehat{RC}$ & --- & \\nfxpRC\\ (\\nfxpSErc) \\\\")
    tex.append("Log-likelihood & $\\bcLL$ & $\\nfxpLL$ \\\\")
    tex.append("Policy accuracy & \\bcAcc & \\nfxpAcc \\\\")
    tex.append("Analytical SEs & No & Yes \\\\")
    tex.append("Time (s) & \\bcTime & \\nfxpTime \\\\")
    tex.append("\\bottomrule")
    tex.append("\\end{tabular*}")
    tex.append("\\end{table}")

    OUT.write_text("\n".join(tex) + "\n")
    print(f"\n  Wrote {OUT}")

    # Also save JSON for reproducibility
    OUT.with_suffix(".json").write_text(json.dumps(results, indent=2))


if __name__ == "__main__":
    main()
