#!/usr/bin/env python3
"""Generate NFXP primer results from the known-truth DGP harness.

This replaces the old Rust-bus-only primer simulation. The NFXP primer should
use the same canonical synthetic DGP as the estimator validation harness, with
known reward, value, policy, and Type A/B/C counterfactual oracle objects.

Usage:
    cd /path/to/econirl
    PYTHONPATH=src:. python papers/econirl_package/primers/nfxp/nfxp_run.py
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
TEX_OUT = HERE / "nfxp_results.tex"
DEFAULT_OUTPUT_DIR = Path("/tmp/econirl_nfxp_primer_known_truth")
CELL_ID = "canonical_low_action"
ESTIMATOR = "NFXP"

for path in (ROOT, ROOT / "src"):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from experiments.known_truth import (  # noqa: E402
    build_known_truth_dgp,
    get_cell,
    run_cell_estimator,
)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cell-id", default=CELL_ID)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--show-progress", action="store_true", default=True)
    parser.add_argument("--quiet-progress", action="store_false", dest="show_progress")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    print("NFXP primer: running known-truth validation")
    print(f"  cell: {args.cell_id}")
    print(f"  estimator: {ESTIMATOR}")
    print(f"  output_dir: {args.output_dir}")

    run_dir = run_cell_estimator(
        args.cell_id,
        ESTIMATOR,
        args.output_dir,
        smoke=False,
        show_progress=args.show_progress,
        verbose=args.verbose,
    )
    result_path = run_dir / "result.json"
    result = json.loads(result_path.read_text(encoding="utf-8"))

    cell = get_cell(args.cell_id)
    dgp = build_known_truth_dgp(cell.dgp_config)
    tex = render_results_tex(result, dgp)
    TEX_OUT.write_text(tex, encoding="utf-8")

    print(f"  result: {result_path}")
    print(f"  wrote: {TEX_OUT}")


def render_results_tex(result: dict[str, Any], dgp: Any) -> str:
    summary = result["summary"]
    diagnostics = result["diagnostics"]
    metrics = result["metrics"]
    gates = result["gates"]
    simulation = result["simulation"]
    metadata = summary["metadata"]

    names = list(summary["parameter_names"])
    estimates = np.asarray(summary["parameters"], dtype=float)
    standard_errors = np.asarray(summary["standard_errors"], dtype=float)
    truth = np.asarray(dgp.homogeneous_parameters, dtype=float)
    errors = estimates - truth

    lines: list[str] = []
    add = lines.append

    add("% Auto-generated by nfxp_run.py. Do not edit by hand.")
    add("% Known-truth DGP cell: canonical_low_action")
    add("")
    add(r"\section{Generated Validation Results}")
    add(
        "This section is generated by \\texttt{nfxp\\_run.py} from the "
        "\\texttt{experiments.known\\_truth} harness and the canonical "
        "known-truth DGP."
    )
    add("")

    add(r"\subsection{Pre-Estimation Checks}")
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Pre-estimation checks from the known-truth NFXP run.}")
    add(r"\begin{tabular}{lrl}")
    add(r"\toprule")
    add(r"Check & Value & Status \\")
    add(r"\midrule")
    add(
        f"Feature rank & {diagnostics['feature_rank']} / "
        f"{diagnostics['num_features']} & {status(not diagnostics['errors'])} \\\\"
    )
    add(f"Feature condition number & {fmt(diagnostics['condition_number'], 3)} & pass \\\\")
    add(
        "Transition row error & "
        f"${sci(diagnostics['max_transition_row_error'])}$ & pass \\\\"
    )
    add(
        f"Observed states & {diagnostics['observed_states']} / "
        f"{diagnostics['num_states']} & pass \\\\"
    )
    add(
        f"State-action coverage & {fmt(diagnostics['state_action_coverage'], 3)} "
        "& pass \\\\"
    )
    shares = ", ".join(fmt(value, 3) for value in diagnostics["action_shares"])
    add(f"Action shares & {shares} & pass \\\\")
    add(f"Minimum action share & {fmt(diagnostics['min_action_share'], 3)} & pass \\\\")
    add(f"Exit/absorbing anchor & {tf(diagnostics['anchor_valid'])} & pass \\\\")
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")

    add(r"\subsection{Estimator Fit}")
    add(
        "The medium-scale validation run uses "
        f"{int(simulation['n_individuals']):,} individuals, "
        f"{int(simulation['n_periods']):,} periods per individual, and "
        f"{int(summary['num_observations']):,} observations."
    )
    add("")
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Known-truth NFXP run summary.}")
    add(r"\begin{tabular}{lr}")
    add(r"\toprule")
    add(r"Quantity & Value \\")
    add(r"\midrule")
    add(f"Converged & {tf(summary['converged'])} \\\\")
    add(f"Outer iterations & {int(summary['num_iterations'])} \\\\")
    add(f"Log-likelihood & {fmt(summary['log_likelihood'], 4)} \\\\")
    add(f"Estimation time & {fmt(summary['estimation_time'], 2)} seconds \\\\")
    add(f"Function evaluations & {int(metadata['num_function_evals'])} \\\\")
    add(f"Total inner iterations & {int(metadata['num_inner_iterations'])} \\\\")
    add(f"Final inner iterations & {int(metadata['final_inner_iterations'])} \\\\")
    add(f"Inner solver & {metadata['inner_solver']} \\\\")
    add(f"Outer optimizer & {metadata['optimizer']} \\\\")
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")

    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Parameter recovery.}")
    add(r"\begin{tabular}{lrrrr}")
    add(r"\toprule")
    add(r"Parameter & Truth & Estimate & SE & Error \\")
    add(r"\midrule")
    for name, true_value, estimate, se, error in zip(
        names, truth, estimates, standard_errors, errors, strict=True
    ):
        add(
            f"{tt(name)} & {fmt(true_value, 6)} & {fmt(estimate, 6)} & "
            f"{fmt(se, 6)} & {fmt(error, 6)} \\\\"
        )
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")

    parameter_metrics = metrics["parameters"]
    policy_metrics = metrics["policy"]
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Recovery metrics.}")
    add(r"\begin{tabular}{lr}")
    add(r"\toprule")
    add(r"Metric & Value \\")
    add(r"\midrule")
    add(f"Parameter RMSE & {fmt(parameter_metrics['rmse'], 6)} \\\\")
    add(f"Parameter relative RMSE & {fmt(parameter_metrics['relative_rmse'], 6)} \\\\")
    add(
        "Parameter cosine similarity & "
        f"{fmt(parameter_metrics['cosine_similarity'], 6)} \\\\"
    )
    add(f"Reward RMSE & {fmt(metrics['reward_rmse'], 6)} \\\\")
    add(f"Value RMSE & {fmt(metrics['value_rmse'], 6)} \\\\")
    add(f"Q RMSE & {fmt(metrics['q_rmse'], 6)} \\\\")
    add(f"Policy KL & ${sci(policy_metrics['kl'])}$ \\\\")
    add(f"Policy total variation & {fmt(policy_metrics['tv'], 6)} \\\\")
    add(f"Policy max state L1 & {fmt(policy_metrics['linf'], 6)} \\\\")
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")

    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Hard recovery gates.}")
    add(r"\begin{tabular}{llrl}")
    add(r"\toprule")
    add(r"Gate & Threshold & Value & Status \\")
    add(r"\midrule")
    for gate in gates:
        add(
            f"{tex_text(gate['name'])} & {gate_threshold(gate)} & "
            f"{gate_value(gate['value'])} & {status(gate['passed'])} \\\\"
        )
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")
    add(
        "The estimates are not exactly equal to truth because the panel is "
        "finite. The validation target is recovery within strict tolerances, "
        "not exact equality in one finite sample."
    )
    add("")

    add(r"\subsection{Counterfactual Recovery}")
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Counterfactual types.}")
    add(r"\begin{tabular}{lll}")
    add(r"\toprule")
    add(r"Type & Intervention & Purpose \\")
    add(r"\midrule")
    add(r"Type A & Shift reward, hold transitions fixed & Payoff counterfactual \\")
    add(r"Type B & Change transitions, hold reward fixed & State-dynamics counterfactual \\")
    add(r"Type C & Disable one non-anchor action & Action-set/design counterfactual \\")
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Counterfactual recovery against known oracle objects.}")
    add(r"\begin{tabular}{lrrrr}")
    add(r"\toprule")
    add(r"Counterfactual & Policy TV & Policy KL & Value RMSE & Regret \\")
    add(r"\midrule")
    for kind, label in (
        ("type_a", "Type A"),
        ("type_b", "Type B"),
        ("type_c", "Type C"),
    ):
        cf = metrics["counterfactuals"][kind]
        add(
            f"{label} & {fmt(cf['policy']['tv'], 6)} & ${sci(cf['policy']['kl'])}$ & "
            f"{fmt(cf['value_rmse'], 6)} & {fmt(cf['regret'], 6)} \\\\"
        )
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")
    add(
        "These regrets are small because the recovered reward is close enough "
        "to the true reward that re-solving the intervened model produces "
        "almost the same policy as the oracle."
    )
    add("")

    return "\n".join(lines) + "\n"


def fmt(value: float, digits: int = 4) -> str:
    return f"{float(value):.{digits}f}"


def sci(value: float) -> str:
    mantissa, exponent = f"{float(value):.2e}".split("e")
    return rf"{mantissa}\times 10^{{{int(exponent)}}}"


def tf(value: bool) -> str:
    return "true" if bool(value) else "false"


def status(passed: bool) -> str:
    return "pass" if bool(passed) else "fail"


def tt(value: str) -> str:
    return r"\texttt{" + tex_text(value) + "}"


def tex_text(value: str) -> str:
    return (
        str(value)
        .replace("\\", r"\textbackslash{}")
        .replace("_", r"\_")
        .replace("%", r"\%")
        .replace("&", r"\&")
        .replace("#", r"\#")
    )


def gate_threshold(gate: dict[str, Any]) -> str:
    if gate["operator"] == "is":
        return tf(gate["threshold"])
    operator = r"$\leq$" if gate["operator"] == "<=" else r"$\geq$"
    return f"{operator} {gate_value(gate['threshold'])}"


def gate_value(value: Any) -> str:
    if isinstance(value, bool):
        return tf(value)
    if isinstance(value, (int, float)):
        return fmt(value, 6)
    return tex_text(str(value))


if __name__ == "__main__":
    main()
