#!/usr/bin/env python3
"""Generate MPEC primer results from the known-truth DGP harness.

The MPEC primer uses the same canonical synthetic DGP as the estimator
validation harness. No real data are used. The main run is a hard-gated
Su-Judd constrained-likelihood validation with SLSQP, Bellman equality
constraints, and robust standard errors.

Usage:
    cd /path/to/econirl
    PYTHONPATH=src:. python validation/estimators/mpec/run.py
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path
from typing import Any

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
JSON_OUT = ROOT / "validation" / "results" / "mpec.json"
DEFAULT_OUTPUT_DIR = Path("/tmp/econirl_mpec_primer_known_truth")
CELL_ID = "canonical_low_action"
ESTIMATOR = "MPEC"
PAPER_TARGET = "Su-Judd constrained maximum likelihood for tabular DDC"
RELEASE_STATUS = "Certified"

for path in (HERE.parent, ROOT, ROOT / "src"):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from validation_display import validation_context  # noqa: E402
from validation.known_truth import (  # noqa: E402
    build_known_truth_dgp,
    get_cell,
    run_cell_estimator,
    to_jsonable,
)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cell-id", default=CELL_ID)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--show-progress", action="store_true", default=True)
    parser.add_argument("--quiet-progress", action="store_false", dest="show_progress")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    print("MPEC primer: running known-truth validation")
    print(f"  cell: {args.cell_id}")
    print(f"  estimator: {ESTIMATOR}")
    print(f"  output_dir: {args.output_dir}")

    run_dir = run_cell_estimator(
        args.cell_id,
        ESTIMATOR,
        args.output_dir,
        smoke=False,
        show_progress=args.show_progress,
        verbose=args.verbose,
    )
    result_path = run_dir / "result.json"
    result = json.loads(result_path.read_text(encoding="utf-8"))

    cell = get_cell(args.cell_id)
    dgp = build_known_truth_dgp(cell.dgp_config)
    JSON_OUT.write_text(
        json.dumps(compact_payload(result), indent=2, sort_keys=True, allow_nan=False)
        + "\n",
        encoding="utf-8",
    )
    tex = render_results_tex(result, dgp)

    print(f"  result: {result_path}")
    print(f"  wrote: {JSON_OUT}")


def compact_payload(result: dict[str, Any]) -> dict[str, Any]:
    """Return the repo-local machine-readable release artifact."""

    return {
        "estimator": ESTIMATOR,
        "paper_target": PAPER_TARGET,
        "release_status": RELEASE_STATUS,
        "primary_cell_id": result.get("cell", {}).get("cell_id", CELL_ID),
        "result": _finite_jsonable(result),
    }


def _finite_jsonable(value: Any) -> Any:
    """Return strict-JSON-compatible values for public artifacts."""

    value = to_jsonable(value)
    if isinstance(value, dict):
        return {key: _finite_jsonable(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_finite_jsonable(item) for item in value]
    if isinstance(value, float) and not math.isfinite(value):
        return None
    return value


def render_results_tex(result: dict[str, Any], dgp: Any) -> str:
    summary = result["summary"]
    diagnostics = result["diagnostics"]
    metrics = result["metrics"]
    gates = result["gates"]
    simulation = result["simulation"]
    metadata = summary["metadata"]

    names = list(summary["parameter_names"])
    estimates = np.asarray(summary["parameters"], dtype=float)
    standard_errors = np.asarray(summary["standard_errors"], dtype=float)
    truth = np.asarray(dgp.homogeneous_parameters, dtype=float)
    errors = estimates - truth

    lines: list[str] = []
    add = lines.append

    add("% Auto-generated by mpec_run.py. Do not edit by hand.")
    add("% Known-truth DGP cell: canonical_low_action")
    add("")
    add(r"\section{Known-Truth Validation Results}")
    add(
        "This validation uses the low-dimensional action-dependent DGP with "
        "known reward, value, policy, and counterfactual oracle objects."
    )
    add("")
    add(r"\subsection{Validation Design Context}")
    cell_id = result.get("cell", {}).get("cell_id", CELL_ID)
    add(validation_context([cell_id]))
    add("")

    add(r"\subsection{Pre-Estimation Checks}")
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Pre-estimation checks from the known-truth MPEC run.}")
    add(r"\begin{tabular}{lrl}")
    add(r"\toprule")
    add(r"Check & Value & Status \\")
    add(r"\midrule")
    add(
        f"Feature rank & {diagnostics['feature_rank']} / "
        f"{diagnostics['num_features']} & {status(not diagnostics['errors'])} \\\\"
    )
    add(f"Feature condition number & {fmt(diagnostics['condition_number'], 3)} & pass \\\\")
    add(
        "Transition row error & "
        f"${sci(diagnostics['max_transition_row_error'])}$ & pass \\\\"
    )
    add(
        f"Observed states & {diagnostics['observed_states']} / "
        f"{diagnostics['num_states']} & pass \\\\"
    )
    add(
        f"State-action coverage & {fmt(diagnostics['state_action_coverage'], 3)} "
        "& pass \\\\"
    )
    shares = ", ".join(fmt(value, 3) for value in diagnostics["action_shares"])
    add(f"Action shares & {shares} & pass \\\\")
    add(f"Minimum action share & {fmt(diagnostics['min_action_share'], 3)} & pass \\\\")
    add(f"Exit/absorbing anchor & {tf(diagnostics['anchor_valid'])} & pass \\\\")
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")

    add(r"\subsection{Estimator Fit}")
    add(
        "The medium-scale validation run uses "
        f"{int(simulation['n_individuals']):,} individuals, "
        f"{int(simulation['n_periods']):,} periods per individual, and "
        f"{int(summary['num_observations']):,} observations."
    )
    add("")
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Known-truth MPEC run summary.}")
    add(r"\begin{tabular}{lr}")
    add(r"\toprule")
    add(r"Quantity & Value \\")
    add(r"\midrule")
    add(f"Converged & {tf(summary['converged'])} \\\\")
    add(f"SQP iterations & {int(summary['num_iterations'])} \\\\")
    add(f"Log-likelihood & {fmt(summary['log_likelihood'], 4)} \\\\")
    add(f"Estimation time & {fmt(summary['estimation_time'], 2)} seconds \\\\")
    add(f"Solver & {tex_text(metadata['method'])} \\\\")
    add(f"SciPy success & {tf(metadata['scipy_success'])} \\\\")
    add(
        "Final Bellman constraint violation & "
        f"${sci(metadata['final_constraint_violation'])}$ \\\\"
    )
    add(f"Standard errors finite & {tf(np.isfinite(standard_errors).all())} \\\\")
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")

    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Parameter recovery.}")
    add(r"\begin{tabular}{lrrrr}")
    add(r"\toprule")
    add(r"Parameter & Truth & Estimate & SE & Error \\")
    add(r"\midrule")
    for name, true_value, estimate, se, error in zip(
        names, truth, estimates, standard_errors, errors, strict=True
    ):
        add(
            f"{tt(name)} & {fmt(true_value, 6)} & {fmt(estimate, 6)} & "
            f"{fmt(se, 6)} & {fmt(error, 6)} \\\\"
        )
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")

    parameter_metrics = metrics["parameters"]
    policy_metrics = metrics["policy"]
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Recovery metrics.}")
    add(r"\begin{tabular}{lr}")
    add(r"\toprule")
    add(r"Metric & Value \\")
    add(r"\midrule")
    add(f"Parameter RMSE & {fmt(parameter_metrics['rmse'], 6)} \\\\")
    add(f"Parameter relative RMSE & {fmt(parameter_metrics['relative_rmse'], 6)} \\\\")
    add(
        "Parameter cosine similarity & "
        f"{fmt(parameter_metrics['cosine_similarity'], 6)} \\\\"
    )
    add(f"Reward RMSE & {fmt(metrics['reward_rmse'], 6)} \\\\")
    add(f"Value RMSE & {fmt(metrics['value_rmse'], 6)} \\\\")
    add(f"Q RMSE & {fmt(metrics['q_rmse'], 6)} \\\\")
    add(f"Policy KL & ${sci(policy_metrics['kl'])}$ \\\\")
    add(f"Policy total variation & {fmt(policy_metrics['tv'], 6)} \\\\")
    add(f"Policy max state L1 & {fmt(policy_metrics['linf'], 6)} \\\\")
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")

    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Hard recovery gates.}")
    add(r"\begin{tabular}{llrl}")
    add(r"\toprule")
    add(r"Gate & Threshold & Value & Status \\")
    add(r"\midrule")
    for gate in gates:
        add(
            f"{tex_text(gate['name'])} & {gate_threshold(gate)} & "
            f"{gate_value(gate['value'])} & {status(gate['passed'])} \\\\"
        )
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")

    add(r"\subsection{Counterfactual Recovery}")
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Counterfactual recovery against known oracle objects.}")
    add(r"\begin{tabular}{lrrrr}")
    add(r"\toprule")
    add(r"Counterfactual & Policy TV & Policy KL & Value RMSE & Regret \\")
    add(r"\midrule")
    for kind, label in (
        ("type_a", "Type A"),
        ("type_b", "Type B"),
        ("type_c", "Type C"),
    ):
        cf = metrics["counterfactuals"][kind]
        add(
            f"{label} & {fmt(cf['policy']['tv'], 6)} & "
            f"${sci(cf['policy']['kl'])}$ & "
            f"{fmt(cf['value_rmse'], 6)} & {fmt(cf['regret'], 6)} \\\\"
        )
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")

    return "\n".join(lines) + "\n"


def fmt(value: float | None, digits: int = 4) -> str:
    if value is None:
        return "---"
    return f"{float(value):.{digits}f}"


def sci(value: float) -> str:
    mantissa, exponent = f"{float(value):.2e}".split("e")
    return rf"{mantissa}\times 10^{{{int(exponent)}}}"


def tf(value: bool) -> str:
    return "true" if bool(value) else "false"


def status(passed: bool) -> str:
    return "pass" if bool(passed) else "fail"


def tt(value: str) -> str:
    return r"\texttt{" + tex_text(value) + "}"


def tex_text(value: str) -> str:
    return (
        str(value)
        .replace("\\", r"\textbackslash{}")
        .replace("_", r"\_")
        .replace("%", r"\%")
        .replace("&", r"\&")
        .replace("#", r"\#")
    )


def gate_threshold(gate: dict[str, Any]) -> str:
    if gate["operator"] == "is":
        return tf(gate["threshold"])
    operator = r"$\leq$" if gate["operator"] == "<=" else r"$\geq$"
    return f"{operator} {gate_value(gate['threshold'])}"


def gate_value(value: Any) -> str:
    if isinstance(value, bool):
        return tf(value)
    if isinstance(value, (int, float)):
        return fmt(value, 6)
    return tex_text(str(value))


if __name__ == "__main__":
    main()
