#!/usr/bin/env python3
"""
AIRL Primer -- Companion simulation script.

Runs NFXP and AIRL on a small serialized content MDP (51 states, 3 actions)
with known ground truth. Writes results to airl_results.tex for automatic
inclusion in the primer PDF.

Usage:
    cd papers/econirl_package/primers
    python airl_run.py
    pdflatex airl.tex
"""

import json
import sys
import time
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

import jax.numpy as jnp
import numpy as np

from econirl.core.bellman import SoftBellmanOperator
from econirl.core.solvers import value_iteration
from econirl.core.types import DDCProblem, Panel, Trajectory
from econirl.estimation.adversarial.airl import AIRLEstimator, AIRLConfig
from econirl.estimation.nfxp import NFXPEstimator
from econirl.preferences.action_reward import ActionDependentReward

# ---------------------------------------------------------------------------
# Environment (same as lsw_replication.py, simplified)
# ---------------------------------------------------------------------------

N_EPISODES = 50
N_STATES = N_EPISODES + 1
N_ACTIONS = 3
ABSORBING = N_EPISODES
EXIT_ACTION = 2
DISCOUNT = 0.90
N_FEATURES = 6

TRUE_PARAMS = np.array([-0.3, 2.0, 1.5, -0.8, 0.5, 0.8])
PARAM_NAMES = ["buy_cost", "quality_buy", "cliffhanger_buy",
               "wait_cost", "quality_wait", "progress_buy"]


def build_environment(seed=42):
    rng = np.random.default_rng(seed)
    quality = np.zeros(N_EPISODES)
    for book in range(5):
        for ep in range(10):
            s = book * 10 + ep
            base = 0.5 + 0.3 * np.sin(np.pi * ep / 9)
            quality[s] = np.clip(base + 0.1 * rng.standard_normal(), 0.1, 1.0)
    cliffhanger = (quality > 0.7).astype(float)
    book_progress = np.array([(s % 10) / 9.0 for s in range(N_EPISODES)])

    T = np.zeros((N_ACTIONS, N_STATES, N_STATES))
    for s in range(N_EPISODES):
        next_ep = s + 1
        if next_ep >= N_EPISODES or (s + 1) % 10 == 0:
            T[0, s, ABSORBING] = 1.0
        else:
            T[0, s, next_ep] = 1.0
        T[1, s, s] = 1.0
        T[2, s, ABSORBING] = 1.0
    for a in range(N_ACTIONS):
        T[a, ABSORBING, ABSORBING] = 1.0

    features = np.zeros((N_STATES, N_ACTIONS, N_FEATURES))
    for s in range(N_EPISODES):
        features[s, 0, 0] = 1.0
        features[s, 0, 1] = quality[s]
        features[s, 0, 2] = cliffhanger[s]
        features[s, 1, 3] = 1.0
        features[s, 1, 4] = quality[s]
        features[s, 0, 5] = book_progress[s]

    return {
        "transitions": jnp.array(T, dtype=jnp.float32),
        "features": jnp.array(features, dtype=jnp.float32),
        "problem": DDCProblem(N_STATES, N_ACTIONS, DISCOUNT),
        "utility": ActionDependentReward(
            jnp.array(features, dtype=jnp.float32), PARAM_NAMES
        ),
        "reward": jnp.einsum("sak,k->sa",
                             jnp.array(features, dtype=jnp.float32),
                             jnp.array(TRUE_PARAMS, dtype=jnp.float32)),
    }


def generate_panel(env, n_users=2000, n_books=3, seed=42):
    rng = np.random.default_rng(seed)
    operator = SoftBellmanOperator(env["problem"], env["transitions"])
    result = value_iteration(operator, env["reward"], tol=1e-10, max_iter=5000)
    policy = np.array(result.policy)

    trajectories = []
    for i in range(n_users):
        books = rng.choice(5, size=n_books, replace=False)
        for book in books:
            state = book * 10
            states, actions, next_states = [], [], []
            for _ in range(20):
                if state == ABSORBING:
                    break
                probs = np.maximum(policy[state], 0)
                probs /= probs.sum()
                action = rng.choice(N_ACTIONS, p=probs)
                ns = int(jnp.argmax(env["transitions"][action, state]))
                states.append(state)
                actions.append(action)
                next_states.append(ns)
                state = ns
            if len(states) >= 2:
                trajectories.append(Trajectory(
                    states=jnp.array(states, dtype=jnp.int32),
                    actions=jnp.array(actions, dtype=jnp.int32),
                    next_states=jnp.array(next_states, dtype=jnp.int32),
                    individual_id=i,
                ))
    return Panel(trajectories=trajectories)


def write_results_tex(nfxp_params, airl_params, airl_time, path="airl_results.tex"):
    """Write a .tex snippet with the results table body."""
    lines = ["% Auto-generated by airl_run.py -- do not edit by hand\n"]
    for i, name in enumerate(PARAM_NAMES):
        true = TRUE_PARAMS[i]
        nfxp = nfxp_params[i] if nfxp_params is not None else float("nan")
        airl = airl_params[i] if airl_params is not None else float("nan")
        tex_name = name.replace("_", r"\_")
        lines.append(
            f"{tex_name} & ${true:.2f}$ & ${nfxp:.2f}$ & ${airl:.2f}$ \\\\\n"
        )
    Path(path).write_text("".join(lines))
    print(f"Results written to {path}")


def main():
    print("Building environment...")
    env = build_environment()

    print("Generating panel...")
    panel = generate_panel(env)
    n_obs = sum(len(t.states) for t in panel.trajectories)
    print(f"  {len(panel.trajectories)} trajectories, {n_obs} observations")

    # NFXP
    print("Running NFXP...")
    t0 = time.time()
    nfxp = NFXPEstimator(se_method="robust")
    nfxp_result = nfxp.estimate(
        panel, env["utility"], env["problem"], env["transitions"]
    )
    nfxp_params = np.array(nfxp_result.parameters)
    print(f"  NFXP time: {time.time() - t0:.1f}s")

    # AIRL
    print("Running AIRL (linear, conservative VI)...")
    t0 = time.time()
    airl = AIRLEstimator(AIRLConfig(
        reward_type="linear",
        max_rounds=500,
        reward_lr=0.01,
        reward_weight_decay=0.01,
        discriminator_steps=1,
        policy_step_size=0.1,
        use_shaping=True,
        convergence_tol=1e-6,
        verbose=True,
    ))
    airl_result = airl.estimate(
        panel, env["utility"], env["problem"], env["transitions"]
    )
    airl_params = np.array(airl_result.parameters)
    airl_time = time.time() - t0
    print(f"  AIRL time: {airl_time:.1f}s")

    # Print summary
    print(f"\n{'Parameter':>20} {'True':>8} {'NFXP':>8} {'AIRL':>8}")
    print("-" * 48)
    for i, name in enumerate(PARAM_NAMES):
        print(f"{name:>20} {TRUE_PARAMS[i]:>8.2f} {nfxp_params[i]:>8.2f} {airl_params[i]:>8.2f}")

    # Write tex snippet
    write_results_tex(nfxp_params, airl_params, airl_time)

    # Also save JSON
    out = {
        "true": dict(zip(PARAM_NAMES, TRUE_PARAMS.tolist())),
        "nfxp": dict(zip(PARAM_NAMES, nfxp_params.tolist())),
        "airl": dict(zip(PARAM_NAMES, airl_params.tolist())),
        "airl_time": airl_time,
        "n_trajectories": len(panel.trajectories),
        "n_observations": n_obs,
    }
    Path("airl_results.json").write_text(json.dumps(out, indent=2))
    print("JSON saved to airl_results.json")


if __name__ == "__main__":
    main()
