#!/usr/bin/env python3
"""IQ-Learn Primer — show penalized MLE trade-off vs NFXP.

Key result: IQ-Learn trades log-likelihood for smaller implied reward.
NFXP maximizes fit alone. Both recover similar policies.

Usage:  python iq_learn_run.py
Output: iq_learn_results.tex, iq_learn_results.json
"""

import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "src"))

import jax.numpy as jnp

OUT = Path(__file__).resolve().parent / "iq_learn_results.tex"
JSON = Path(__file__).resolve().parent / "iq_learn_results.json"


def main():
    from econirl.environments.rust_bus import RustBusEnvironment
    from econirl.estimation.iq_learn import IQLearnEstimator, IQLearnConfig
    from econirl.estimation.nfxp import NFXPEstimator
    from econirl.preferences.linear import LinearUtility

    env = RustBusEnvironment(
        operating_cost=0.001, replacement_cost=3.0,
        num_mileage_bins=90, discount_factor=0.9999,
    )
    panel = env.generate_panel(n_individuals=200, n_periods=100, seed=42)
    utility = LinearUtility.from_environment(env)
    true = jnp.array([0.001, 3.0])

    results = {}

    # NFXP
    print("Running NFXP...")
    t0 = time.time()
    nfxp = NFXPEstimator().estimate(
        panel=panel, utility=utility,
        problem=env.problem_spec, transitions=env.transition_matrices,
    )
    results["nfxp"] = {
        "params": [float(x) for x in nfxp.parameters],
        "ll": float(nfxp.log_likelihood) if nfxp.log_likelihood is not None else 0.0,
        "time": time.time() - t0,
    }
    print(f"  NFXP: {nfxp.parameters}, LL={results['nfxp']['ll']:.1f}")

    # IQ-Learn
    print("Running IQ-Learn...")
    t0 = time.time()
    iq = IQLearnEstimator(config=IQLearnConfig(alpha=1.0))
    iq_result = iq.estimate(
        panel=panel, utility=utility,
        problem=env.problem_spec, transitions=env.transition_matrices,
    )
    results["iq_learn"] = {
        "params": [float(x) for x in iq_result.parameters[:2]],
        "ll": float(iq_result.log_likelihood) if iq_result.log_likelihood is not None else 0.0,
        "time": time.time() - t0,
    }
    print(f"  IQ: {iq_result.parameters[:2]}, LL={results['iq_learn']['ll']:.1f}")

    # Write
    with open(JSON, "w") as f:
        json.dump(results, f, indent=2)

    n, iq_r, nf = results["nfxp"], results["iq_learn"], results["nfxp"]
    tex = rf"""% Auto-generated by iq_learn_run.py

\begin{{table}}[H]
\centering\footnotesize
\caption{{IQ-Learn vs NFXP on Rust bus (90 bins, $\beta\!=\!0.9999$). IQ-Learn trades log-likelihood for smaller implied reward.}}
\label{{tab:iq_results}}
\vspace{{-0.5em}}
\begin{{tabular*}}{{\textwidth}}{{@{{\extracolsep{{\fill}}}} l c c c}}
\toprule
 & True & IQ-Learn & NFXP \\
\midrule
Op.\ cost ($\times 10^{{-3}}$) & 1.000 & {iq_r['params'][0]*1000:.3f} & {n['params'][0]*1000:.3f} \\
Repl.\ cost & 3.000 & {iq_r['params'][1]:.3f} & {n['params'][1]:.3f} \\
Log-likelihood & --- & {iq_r['ll']:.1f} & {n['ll']:.1f} \\
Time (sec) & --- & {iq_r['time']:.1f} & {n['time']:.1f} \\
\bottomrule
\end{{tabular*}}
\end{{table}}
"""
    OUT.write_text(tex.strip())
    print(f"\nResults written to {OUT}")


if __name__ == "__main__":
    main()
