#!/usr/bin/env python3
"""NNES Primer — auto-generate results for the LaTeX document.

Runs NNES (NPL Bellman, 2-layer V-network) and NFXP (oracle) on a
simulated panel from the Rust (1987) bus replacement model. Writes
LaTeX macros and a results table to nnes_results.tex.

This script demonstrates the key property of NNES (Nguyen 2025):
the NPL variant recovers structural parameters with valid standard
errors despite using a neural network to approximate the value
function, thanks to the zero Jacobian / Neyman orthogonality property.

Usage:
    cd /path/to/econirl
    python papers/econirl_package/primers/nnes/nnes_run.py
"""

import json
import time
from pathlib import Path

import jax.numpy as jnp
import numpy as np

OUT = Path(__file__).resolve().parent / "nnes_results.tex"

# ---------- DGP settings (Rust 1987) ----------
TRUE_OC = 0.001          # operating cost per mileage bin
TRUE_RC = 3.0            # replacement cost
N_STATES = 90            # mileage bins
DISCOUNT = 0.9999        # beta (high to match benchmark)
N_BUSES = 200            # number of individuals
N_PERIODS = 100          # periods per bus
SEED = 42


def main():
    from econirl.environments.rust_bus import RustBusEnvironment
    from econirl.estimation.nfxp import NFXPEstimator
    from econirl.estimators.nnes import NNES
    from econirl.preferences.linear import LinearUtility
    from econirl.simulation.synthetic import simulate_panel

    n_obs = N_BUSES * N_PERIODS

    print("NNES Primer — generating results")
    print(f"  Environment: Rust bus, {N_STATES} bins, beta={DISCOUNT}")
    print(f"  Data: {N_BUSES} x {N_PERIODS} = {n_obs:,} obs")

    env = RustBusEnvironment(
        operating_cost=TRUE_OC,
        replacement_cost=TRUE_RC,
        num_mileage_bins=N_STATES,
        discount_factor=DISCOUNT,
        seed=SEED,
    )
    problem = env.problem_spec
    transitions = env.transition_matrices
    utility = LinearUtility.from_environment(env)

    panel = simulate_panel(
        env, n_individuals=N_BUSES, n_periods=N_PERIODS,
        seed=SEED + 1000,
    )

    results = {}

    # ── NFXP oracle ──
    print("\n  Running NFXP...")
    nfxp = NFXPEstimator(
        inner_solver="hybrid",
        inner_tol=1e-12,
        inner_max_iter=100000,
        switch_tol=1e-3,
        outer_max_iter=200,
        compute_hessian=True,
        verbose=False,
    )
    t0 = time.time()
    nfxp_res = nfxp.estimate(panel, utility, problem, transitions)
    nfxp_time = time.time() - t0
    nfxp_params = np.asarray(nfxp_res.parameters)
    nfxp_se = np.asarray(nfxp_res.standard_errors)

    results["nfxp"] = {
        "theta_c": float(nfxp_params[0]),
        "RC": float(nfxp_params[1]),
        "se_theta_c": float(nfxp_se[0]),
        "se_RC": float(nfxp_se[1]),
        "ll": float(nfxp_res.log_likelihood),
        "time": nfxp_time,
    }
    print(f"    theta_c={nfxp_params[0]:.6f} (SE {nfxp_se[0]:.6f}), "
          f"RC={nfxp_params[1]:.4f} (SE {nfxp_se[1]:.4f}), "
          f"LL={nfxp_res.log_likelihood:.1f}, time={nfxp_time:.1f}s")

    # ── NNES (NPL variant via sklearn wrapper) ──
    print("\n  Running NNES (NPL)...")
    nnes_model = NNES(
        n_states=N_STATES,
        discount=DISCOUNT,
        bellman="npl",
        hidden_dim=32,
        num_layers=2,
        v_lr=1e-3,
        v_epochs=500,
        n_outer_iterations=10,
        verbose=False,
    )

    # Convert panel to DataFrame for sklearn API
    import pandas as pd
    rows = []
    for traj in panel.trajectories:
        bus_id = traj.individual_id
        for t_idx, (s, a) in enumerate(zip(traj.states, traj.actions)):
            rows.append({"bus_id": int(bus_id), "mileage_bin": int(s), "replaced": int(a)})
    df = pd.DataFrame(rows)

    t0 = time.time()
    nnes_model.fit(df, state="mileage_bin", action="replaced", id="bus_id")
    nnes_time = time.time() - t0

    nnes_params = np.array([nnes_model.params_["theta_c"], nnes_model.params_["RC"]])
    nnes_se_oc = nnes_model.se_["theta_c"] if nnes_model.se_ else float("nan")
    nnes_se_rc = nnes_model.se_["RC"] if nnes_model.se_ else float("nan")
    nnes_se = np.array([nnes_se_oc, nnes_se_rc])
    nnes_ll = nnes_model.log_likelihood_ if nnes_model.log_likelihood_ else float("nan")

    results["nnes"] = {
        "theta_c": float(nnes_params[0]),
        "RC": float(nnes_params[1]),
        "se_theta_c": float(nnes_se[0]),
        "se_RC": float(nnes_se[1]),
        "ll": float(nnes_ll),
        "time": nnes_time,
    }
    print(f"    theta_c={nnes_params[0]:.6f} (SE {nnes_se[0]:.6f}), "
          f"RC={nnes_params[1]:.4f} (SE {nnes_se[1]:.4f}), "
          f"LL={nnes_ll:.1f}, time={nnes_time:.1f}s")

    ll_gap = abs(float(nnes_ll) - float(nfxp_res.log_likelihood))
    print(f"\n  LL gap: {ll_gap:.2f}")

    # ── Write LaTeX ──
    tex = []
    tex.append("% Auto-generated by nnes_run.py — do not edit by hand")
    tex.append(f"% Rust bus {N_STATES} bins, beta={DISCOUNT}, {n_obs} obs, seed={SEED}")
    tex.append("")
    tex.append(f"\\newcommand{{\\nnesNstates}}{{{N_STATES}}}")
    tex.append(f"\\newcommand{{\\nnesBeta}}{{{DISCOUNT}}}")
    tex.append(f"\\newcommand{{\\nnesNobs}}{{{n_obs:,}}}")
    tex.append(f"\\newcommand{{\\nnesTrueOC}}{{{TRUE_OC}}}")
    tex.append(f"\\newcommand{{\\nnesTrueRC}}{{{TRUE_RC}}}")
    tex.append("")
    # NFXP
    tex.append(f"\\newcommand{{\\nnesNfxpOC}}{{{float(nfxp_params[0]):.6f}}}")
    tex.append(f"\\newcommand{{\\nnesNfxpRC}}{{{float(nfxp_params[1]):.4f}}}")
    tex.append(f"\\newcommand{{\\nnesNfxpSEOC}}{{{float(nfxp_se[0]):.6f}}}")
    tex.append(f"\\newcommand{{\\nnesNfxpSERC}}{{{float(nfxp_se[1]):.4f}}}")
    tex.append(f"\\newcommand{{\\nnesNfxpLL}}{{{float(nfxp_res.log_likelihood):.1f}}}")
    tex.append(f"\\newcommand{{\\nnesNfxpTime}}{{{nfxp_time:.1f}}}")
    tex.append("")
    # NNES
    tex.append(f"\\newcommand{{\\nnesOC}}{{{float(nnes_params[0]):.6f}}}")
    tex.append(f"\\newcommand{{\\nnesRC}}{{{float(nnes_params[1]):.4f}}}")
    tex.append(f"\\newcommand{{\\nnesSEOC}}{{{float(nnes_se[0]):.6f}}}")
    tex.append(f"\\newcommand{{\\nnesSERC}}{{{float(nnes_se[1]):.4f}}}")
    tex.append(f"\\newcommand{{\\nnesLL}}{{{float(nnes_ll):.1f}}}")
    tex.append(f"\\newcommand{{\\nnesTime}}{{{nnes_time:.1f}}}")
    tex.append(f"\\newcommand{{\\nnesLLgap}}{{{ll_gap:.2f}}}")
    tex.append("")

    # Embedded results table
    tex.append("\\begin{table}[h!]")
    tex.append("\\centering\\small")
    tex.append(f"\\caption{{Rust bus engine (\\nnesNstates\\ bins, "
               f"$\\beta=\\nnesBeta$, \\nnesNobs\\ obs). "
               f"NNES uses a 2-layer ReLU network with 32 hidden units.}}")
    tex.append("\\label{tab:nnes_results}")
    tex.append("\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}} l r r r}")
    tex.append("\\toprule")
    tex.append("& True & NFXP & NNES \\\\")
    tex.append("\\midrule")
    tex.append("$\\hat\\theta_c$ & \\nnesTrueOC & \\nnesNfxpOC & \\nnesOC \\\\")
    tex.append("SE($\\hat\\theta_c$) & --- & \\nnesNfxpSEOC & \\nnesSEOC \\\\")
    tex.append("$\\widehat{RC}$ & \\nnesTrueRC & \\nnesNfxpRC & \\nnesRC \\\\")
    tex.append("SE($\\widehat{RC}$) & --- & \\nnesNfxpSERC & \\nnesSERC \\\\")
    tex.append("Log-likelihood & --- & $\\nnesNfxpLL$ & $\\nnesLL$ \\\\")
    tex.append("Time (s) & --- & \\nnesNfxpTime & \\nnesTime \\\\")
    tex.append("\\bottomrule")
    tex.append("\\end{tabular*}")
    tex.append("\\end{table}")

    OUT.write_text("\n".join(tex) + "\n")
    print(f"\n  Wrote {OUT}")
    OUT.with_suffix(".json").write_text(json.dumps(results, indent=2, default=float))
    print(f"  Wrote {OUT.with_suffix('.json')}")


if __name__ == "__main__":
    main()
