#!/usr/bin/env python3
"""
MPEC Primer -- Companion simulation (Su & Judd 2012).

Runs MPEC and NFXP on the Rust bus engine (90 states) at three discount
factors. Writes results to mpec_results.tex for automatic inclusion.

Usage:
    cd papers/econirl_package/primers/mpec
    python mpec_run.py
    pdflatex mpec.tex && bibtex mpec && pdflatex mpec.tex && pdflatex mpec.tex
"""

import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[4]))

import jax.numpy as jnp
import numpy as np

from econirl.environments.rust_bus import RustBusEnvironment
from econirl.estimation.mpec import MPECEstimator, MPECConfig
from econirl.estimation.nfxp import NFXPEstimator
from econirl.preferences.linear import LinearUtility

TRUE_OC = 0.001
TRUE_RC = 3.0
N_BINS = 90
BETAS = [0.90, 0.95, 0.99]


def run_one(beta, n_individuals=500, n_periods=100, seed=42):
    """Run MPEC and NFXP at a given discount factor."""
    env = RustBusEnvironment(
        num_mileage_bins=N_BINS,
        operating_cost=TRUE_OC,
        replacement_cost=TRUE_RC,
        discount_factor=beta,
    )
    panel = env.generate_panel(n_individuals=n_individuals, n_periods=n_periods, seed=seed)
    transitions = env.transition_matrices
    problem = env.problem_spec
    utility = LinearUtility(
        feature_matrix=env.feature_matrix,
        parameter_names=env.parameter_names,
    )

    results = {"beta": beta, "n_obs": panel.num_observations}

    # NFXP
    t0 = time.time()
    nfxp = NFXPEstimator(se_method="robust")
    nfxp_result = nfxp.estimate(panel, utility, problem, transitions)
    nfxp_time = time.time() - t0
    results["nfxp"] = {
        "oc": float(nfxp_result.parameters[0]),
        "rc": float(nfxp_result.parameters[1]),
        "ll": float(nfxp_result.log_likelihood),
        "time": nfxp_time,
        "converged": bool(nfxp_result.converged),
    }

    # MPEC
    t0 = time.time()
    mpec = MPECEstimator(MPECConfig(
        solver="augmented_lagrangian",
        max_iter=500,
        tol=1e-10,
        constraint_tol=1e-8,
        rho_initial=1.0,
        rho_growth=10.0,
        rho_max=1e6,
        outer_max_iter=50,
    ))
    mpec_result = mpec.estimate(panel, utility, problem, transitions)
    mpec_time = time.time() - t0
    cv = float(mpec_result.metadata.get("final_constraint_violation", float("nan")))
    results["mpec"] = {
        "oc": float(mpec_result.parameters[0]),
        "rc": float(mpec_result.parameters[1]),
        "ll": float(mpec_result.log_likelihood),
        "time": mpec_time,
        "converged": bool(mpec_result.converged),
        "constraint_violation": cv,
    }

    return results


def write_results_tex(all_results, path="mpec_results.tex"):
    """Write auto-generated table body for the primer."""
    lines = ["% Auto-generated by mpec_run.py -- do not edit by hand\n"]
    for r in all_results:
        beta = r["beta"]
        n = r["nfxp"]
        m = r["mpec"]
        lines.append(
            f"${beta:.2f}$ & ${n['oc']:.6f}$ & ${n['rc']:.4f}$ & ${n['time']:.1f}$s"
            f" & ${m['oc']:.6f}$ & ${m['rc']:.4f}$ & ${m['time']:.1f}$s"
            f" & ${m['constraint_violation']:.1e}$ \\\\\n"
        )
    Path(path).write_text("".join(lines))
    print(f"Results written to {path}")


def main():
    print("=" * 70)
    print("MPEC Primer: Rust Bus Engine (90 states)")
    print(f"True: OC={TRUE_OC}, RC={TRUE_RC}")
    print("=" * 70)

    all_results = []
    for beta in BETAS:
        print(f"\n--- beta = {beta} ---")
        r = run_one(beta)
        all_results.append(r)
        n, m = r["nfxp"], r["mpec"]
        print(f"  NFXP: OC={n['oc']:.6f} RC={n['rc']:.4f} LL={n['ll']:.2f} "
              f"time={n['time']:.1f}s conv={n['converged']}")
        print(f"  MPEC: OC={m['oc']:.6f} RC={m['rc']:.4f} LL={m['ll']:.2f} "
              f"time={m['time']:.1f}s conv={m['converged']} "
              f"CV={m['constraint_violation']:.1e}")

    # Summary
    print(f"\n{'beta':>6} {'NFXP OC':>10} {'MPEC OC':>10} {'True OC':>10} "
          f"{'NFXP RC':>10} {'MPEC RC':>10} {'True RC':>10}")
    print("-" * 68)
    for r in all_results:
        n, m = r["nfxp"], r["mpec"]
        print(f"{r['beta']:>6.2f} {n['oc']:>10.6f} {m['oc']:>10.6f} {TRUE_OC:>10.6f} "
              f"{n['rc']:>10.4f} {m['rc']:>10.4f} {TRUE_RC:>10.4f}")

    write_results_tex(all_results)

    # JSON
    Path("mpec_results.json").write_text(json.dumps(all_results, indent=2))
    print("JSON saved to mpec_results.json")
    print("\nDone.")


if __name__ == "__main__":
    main()
