#!/usr/bin/env python3
"""Generate NNES primer validation results from the known-truth DGP harness.

The NNES primer uses the shared canonical synthetic DGP and enforces the
shared hard known-truth recovery gates.

Usage:
    cd /path/to/econirl
    PYTHONPATH=src:. python papers/econirl_package/primers/nnes/nnes_run.py
"""

from __future__ import annotations

import argparse
import math
import sys
from dataclasses import replace
from pathlib import Path
from typing import Any

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
TEX_OUT = HERE / "nnes_results.tex"
JSON_OUT = HERE / "nnes_results.json"
DEFAULT_OUTPUT_DIR = Path("/tmp/econirl_nnes_primer_known_truth")
DEFAULT_CELL_IDS = ("canonical_low_action", "canonical_high_action")
PRIMARY_CELL_ID = "canonical_high_action"
ESTIMATOR = "NNES"
CELL_ROLES = {
    "canonical_low_action": "sanity check",
    "canonical_high_action": "primary validation",
}
CELL_LABELS = {
    "canonical_low_action": "Low-dimensional",
    "canonical_high_action": "High-dimensional",
}

for path in (ROOT, ROOT / "src"):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from experiments.known_truth import (  # noqa: E402
    build_known_truth_dgp,
    get_cell,
    run_estimator,
    simulate_known_truth_panel,
    stable_hash,
    write_json,
)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--cell-id",
        action="append",
        default=None,
        help=(
            "Known-truth cell to run. May be repeated. "
            "Defaults to canonical_low_action and canonical_high_action."
        ),
    )
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--show-progress", action="store_true", default=True)
    parser.add_argument("--quiet-progress", action="store_false", dest="show_progress")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()
    cell_ids = args.cell_id if args.cell_id is not None else list(DEFAULT_CELL_IDS)

    print("NNES primer: running known-truth validation")
    print(f"  cells: {', '.join(cell_ids)}")
    print(f"  estimator: {ESTIMATOR}")
    print(f"  output_dir: {args.output_dir}")

    records = [
        run_validation_cell(cell_id, args)
        for cell_id in cell_ids
    ]

    write_json(JSON_OUT, compact_payload(records))
    tex = render_results_tex(records)
    TEX_OUT.write_text(tex, encoding="utf-8")

    total_gates = 0
    failed_gates = 0
    for record in records:
        payload = record["payload"]
        failed = [gate for gate in payload["gates"] if not gate.passed]
        total_gates += len(payload["gates"])
        failed_gates += len(failed)
        print(f"  result ({payload['cell'].cell_id}): {record['run_dir'] / 'result.json'}")
        print(
            f"  hard gates ({payload['cell'].cell_id}): "
            f"{len(payload['gates']) - len(failed)} pass, {len(failed)} fail"
        )
    print(f"  wrote: {JSON_OUT}")
    print(f"  wrote: {TEX_OUT}")
    print(f"  hard gates total: {total_gates - failed_gates} pass, {failed_gates} fail")


def run_validation_cell(cell_id: str, args: argparse.Namespace) -> dict[str, Any]:
    cell = get_cell(cell_id)
    dgp = build_known_truth_dgp(cell.dgp_config)
    simulation_config = replace(
        cell.simulation_config,
        show_progress=args.show_progress,
    )
    panel = simulate_known_truth_panel(dgp, simulation_config)

    main_run = run_estimator(
        ESTIMATOR,
        dgp,
        panel,
        smoke=False,
        verbose=args.verbose,
        enforce_gates=True,
    )

    payload = {
        "cell": cell,
        "simulation": simulation_config,
        "estimator": ESTIMATOR,
        "diagnostics": main_run.diagnostics,
        "compatibility": main_run.compatibility,
        "summary": main_run.summary,
        "metrics": main_run.metrics,
        "gates": main_run.gates,
    }
    run_hash = stable_hash(
        {
            "cell": cell.dgp_config.to_dict(),
            "simulation": simulation_config,
            "estimator": ESTIMATOR,
            "primer": "nnes",
            "enforce_gates": True,
        }
    )
    run_dir = args.output_dir / f"{cell_id}_nnes_primer_{run_hash}"
    write_json(run_dir / "result.json", payload)
    return {"payload": payload, "dgp": dgp, "run_dir": run_dir}


def render_results_tex(records: list[dict[str, Any]]) -> str:
    records_by_id = {record["payload"]["cell"].cell_id: record for record in records}
    high_record = records_by_id.get(PRIMARY_CELL_ID)

    lines: list[str] = []
    add = lines.append

    add("% Auto-generated by nnes_run.py. Do not edit by hand.")
    cell_comment = ", ".join(
        record["payload"]["cell"].cell_id
        for record in records
    )
    add("% Known-truth DGP cells: " + cell_comment)
    add("")
    add(r"\section{Generated Validation Results}")
    add(
        "This section is generated by \\texttt{nnes\\_run.py} from the "
        "\\texttt{experiments.known\\_truth} harness. Hard gates are enforced. "
        "The low-dimensional cell is a sanity check; the high-dimensional cell "
        "is the main NNES validation because it exercises the larger state and "
        "reward-feature setting where the neural estimator is meant to matter."
    )
    add("")

    add(r"\subsection{Validation Design}")
    add(
        "Both cells use 2,000 simulated individuals, 80 periods per individual, "
        "known transitions, three actions, homogeneous rewards, and the shared "
        "Type A/B/C counterfactual oracles. The high-dimensional cell is the "
        "primary stress test; the low-dimensional cell checks that the same "
        "implementation still behaves correctly in the easy benchmark."
    )
    add("")
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{NNES known-truth validation cells.}")
    add(r"\begin{tabular}{llrrrrr}")
    add(r"\toprule")
    add(r"Cell & Role & States & State dim. & Reward params & Obs. & Gates \\")
    add(r"\midrule")
    for record in records:
        payload = record["payload"]
        dgp = record["dgp"]
        summary = payload["summary"]
        gates = payload["gates"]
        cell_id = payload["cell"].cell_id
        passed_gates = sum(gate.passed for gate in gates)
        add(
            f"{tex_text(CELL_LABELS.get(cell_id, cell_id))} & "
            f"{tex_text(CELL_ROLES.get(cell_id, 'validation'))} & "
            f"{dgp.problem.num_states} & {dgp.problem.state_dim} & "
            f"{dgp.feature_matrix.shape[-1]} & {int(summary.num_observations):,} & "
            f"{passed_gates}/{len(gates)} \\\\"
        )
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")

    if high_record is not None:
        high = high_record["payload"]
        high_diag = high["diagnostics"]
        add(
            "The high-dimensional DGP passes the pre-estimation checks before "
            "NNES is fit: feature rank is "
            f"{high_diag.feature_rank}/{high_diag.num_features}, the reward-feature "
            f"condition number is {fmt(high_diag.condition_number, 3)}, all "
            f"{high_diag.num_states} states are observed, and state-action "
            f"coverage is {fmt(high_diag.state_action_coverage, 3)}."
        )
        add("")

    add(r"\subsection{Fit Summary}")
    add("")
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{NNES fit summary.}")
    add(r"\begin{tabular}{lrrrr}")
    add(r"\toprule")
    add(r"Cell & Converged & L-BFGS-B iter. & Final V loss & Log likelihood \\")
    add(r"\midrule")
    for record in records:
        payload = record["payload"]
        summary = payload["summary"]
        metadata = summary.metadata
        add(
            f"{tt(payload['cell'].cell_id)} & {tf(summary.converged)} & "
            f"{int(summary.num_iterations)} & "
            f"{fmt(metadata['v_loss_per_outer'][-1], 4)} & "
            f"{fmt(summary.log_likelihood, 1)} \\\\"
        )
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")

    add(
        "The easy cell is very tight. The high-dimensional cell is deliberately "
        "harder: reward, value, and Q errors are larger, but they remain within "
        "the hard gates."
    )
    add("")

    add(r"\subsection{Main Recovery Numbers}")
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Core recovery metrics.}")
    add(r"\begin{tabular}{llrr}")
    add(r"\toprule")
    add(r"Metric & Gate & Low-dimensional & High-dimensional \\")
    add(r"\midrule")
    metric_rows = (
        (
            "Parameter cosine similarity",
            r"$\geq 0.95$",
            lambda record: record["payload"]["metrics"]["parameters"].cosine_similarity,
        ),
        (
            "Parameter relative RMSE",
            r"$\leq 0.30$",
            lambda record: record["payload"]["metrics"]["parameters"].relative_rmse,
        ),
        ("Reward RMSE", r"$\leq 0.08$", lambda record: record["payload"]["metrics"]["reward_rmse"]),
        (
            "Policy total variation",
            r"$\leq 0.03$",
            lambda record: record["payload"]["metrics"]["policy"].tv,
        ),
        ("Value RMSE", r"$\leq 0.20$", lambda record: record["payload"]["metrics"]["value_rmse"]),
        ("Q RMSE", r"$\leq 0.20$", lambda record: record["payload"]["metrics"]["q_rmse"]),
    )
    low_record = records_by_id.get("canonical_low_action")
    for label, gate, getter in metric_rows:
        low_value = getter(low_record) if low_record is not None else None
        high_value = getter(high_record) if high_record is not None else None
        add(
            f"{tex_text(label)} & {gate} & {fmt(low_value, 4)} & "
            f"{fmt(high_value, 4)} \\\\"
        )
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")

    add(r"\subsection{Counterfactual Recovery}")
    add(
        "Each counterfactual gate requires regret below 0.05. All three "
        "counterfactuals pass in both cells."
    )
    add("")
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Counterfactual regret.}")
    add(r"\begin{tabular}{lrrl}")
    add(r"\toprule")
    add(r"Counterfactual & Low-dimensional & High-dimensional & Interpretation \\")
    add(r"\midrule")
    for kind, label, interpretation in (
        ("type_a", "Type A", "reward/state shift"),
        ("type_b", "Type B", "transition change"),
        ("type_c", "Type C", "action restriction"),
    ):
        low_value = (
            low_record["payload"]["metrics"]["counterfactuals"][kind].regret
            if low_record is not None
            else None
        )
        high_value = (
            high_record["payload"]["metrics"]["counterfactuals"][kind].regret
            if high_record is not None
            else None
        )
        add(
            f"{label} & {fmt(low_value, 4)} & {fmt(high_value, 4)} & "
            f"{tex_text(interpretation)} \\\\"
        )
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")

    add(
        "Exact parameter vectors, standard errors, log-likelihoods, policy "
        "distances, and all gate values are written to \\texttt{nnes\\_results.json}. "
        "The PDF reports the decision-critical values rather than printing the "
        "full 32-parameter high-dimensional vector."
    )
    add("")

    add(r"\subsection{Gate Audit}")
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Hard-gate audit by cell.}")
    add(r"\begin{tabular}{lrr}")
    add(r"\toprule")
    add(r"Cell & Passed gates & Failed gates \\")
    add(r"\midrule")
    for record in records:
        payload = record["payload"]
        gates = payload["gates"]
        passed = sum(gate.passed for gate in gates)
        add(
            f"{tt(payload['cell'].cell_id)} & {passed} & {len(gates) - passed} \\\\"
        )
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")

    return "\n".join(lines) + "\n"


def compact_payload(records: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "estimator": ESTIMATOR,
        "primary_cell_id": PRIMARY_CELL_ID,
        "results": [
            compact_cell_payload(record["payload"])
            for record in records
        ],
    }


def compact_cell_payload(payload: dict[str, Any]) -> dict[str, Any]:
    summary = payload["summary"]
    metadata = summary.metadata
    return {
        "cell_id": payload["cell"].cell_id,
        "estimator": payload["estimator"],
        "simulation": payload["simulation"],
        "compatibility": payload["compatibility"],
        "diagnostics": payload["diagnostics"],
        "summary": {
            "parameter_names": summary.parameter_names,
            "parameters": summary.parameters,
            "standard_errors": finite_list(summary.standard_errors),
            "log_likelihood": summary.log_likelihood,
            "converged": summary.converged,
            "num_iterations": summary.num_iterations,
            "num_observations": summary.num_observations,
            "estimation_time": summary.estimation_time,
            "convergence_message": summary.convergence_message,
            "metadata": {
                "profile_mode": metadata.get("profile_mode"),
                "n_outer_iterations": metadata.get("n_outer_iterations"),
                "v_loss_per_outer": metadata.get("v_loss_per_outer"),
            },
        },
        "metrics": payload["metrics"],
        "gates": payload["gates"],
    }


def fmt(value: float | None, digits: int = 4) -> str:
    if value is None:
        return "---"
    number = float(value)
    if not math.isfinite(number):
        return "---"
    return f"{number:.{digits}f}"


def finite_list(values: Any) -> list[float | None]:
    array = np.asarray(values, dtype=float)
    return [float(value) if math.isfinite(float(value)) else None for value in array]


def sci(value: float) -> str:
    number = float(value)
    if not math.isfinite(number):
        return "---"
    mantissa, exponent = f"{number:.2e}".split("e")
    return rf"{mantissa}\times 10^{{{int(exponent)}}}"


def tf(value: bool) -> str:
    return "true" if bool(value) else "false"


def status(passed: bool) -> str:
    return "pass" if bool(passed) else "fail"


def tt(value: str) -> str:
    return r"\texttt{" + tex_text(value) + "}"


def tex_text(value: str) -> str:
    return (
        str(value)
        .replace("\\", r"\textbackslash{}")
        .replace("_", r"\_")
        .replace("%", r"\%")
        .replace("&", r"\&")
        .replace("#", r"\#")
    )


def gate_threshold(gate: Any) -> str:
    if gate.operator == "is":
        return tf(gate.threshold)
    operator = r"$\leq$" if gate.operator == "<=" else r"$\geq$"
    return f"{operator} {gate_value(gate.threshold)}"


def gate_value(value: Any) -> str:
    if isinstance(value, bool):
        return tf(value)
    if isinstance(value, (int, float)):
        return fmt(value, 6)
    return tex_text(str(value))


if __name__ == "__main__":
    main()
