#!/usr/bin/env python3
"""Generate NNES primer validation results from the known-truth DGP harness.

The NNES primer uses the shared canonical synthetic DGP and enforces the
shared hard known-truth recovery gates.

Usage:
    cd /path/to/econirl
    PYTHONPATH=src:. python papers/econirl_package/primers/nnes/nnes_run.py
"""

from __future__ import annotations

import argparse
import math
import sys
from dataclasses import replace
from pathlib import Path
from typing import Any

import numpy as np

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
TEX_OUT = HERE / "nnes_results.tex"
JSON_OUT = HERE / "nnes_results.json"
DEFAULT_OUTPUT_DIR = Path("/tmp/econirl_nnes_primer_known_truth")
CELL_ID = "canonical_low_action"
ESTIMATOR = "NNES"

for path in (ROOT, ROOT / "src"):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from experiments.known_truth import (  # noqa: E402
    build_known_truth_dgp,
    get_cell,
    run_estimator,
    simulate_known_truth_panel,
    stable_hash,
    write_json,
)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cell-id", default=CELL_ID)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--show-progress", action="store_true", default=True)
    parser.add_argument("--quiet-progress", action="store_false", dest="show_progress")
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    print("NNES primer: running known-truth validation")
    print(f"  cell: {args.cell_id}")
    print(f"  estimator: {ESTIMATOR}")
    print(f"  output_dir: {args.output_dir}")

    cell = get_cell(args.cell_id)
    dgp = build_known_truth_dgp(cell.dgp_config)
    simulation_config = replace(
        cell.simulation_config,
        show_progress=args.show_progress,
    )
    panel = simulate_known_truth_panel(dgp, simulation_config)

    main_run = run_estimator(
        ESTIMATOR,
        dgp,
        panel,
        smoke=False,
        verbose=args.verbose,
        enforce_gates=True,
    )

    payload = {
        "cell": cell,
        "simulation": simulation_config,
        "estimator": ESTIMATOR,
        "diagnostics": main_run.diagnostics,
        "compatibility": main_run.compatibility,
        "summary": main_run.summary,
        "metrics": main_run.metrics,
        "gates": main_run.gates,
    }
    run_hash = stable_hash(
        {
            "cell": cell.dgp_config.to_dict(),
            "simulation": simulation_config,
            "estimator": ESTIMATOR,
            "primer": "nnes",
            "enforce_gates": True,
        }
    )
    run_dir = args.output_dir / f"{args.cell_id}_nnes_primer_{run_hash}"
    write_json(run_dir / "result.json", payload)
    write_json(JSON_OUT, compact_payload(payload))

    tex = render_results_tex(payload, dgp)
    TEX_OUT.write_text(tex, encoding="utf-8")

    failed = [gate for gate in main_run.gates if not gate.passed]
    print(f"  result: {run_dir / 'result.json'}")
    print(f"  wrote: {JSON_OUT}")
    print(f"  wrote: {TEX_OUT}")
    print(f"  hard gates: {len(main_run.gates) - len(failed)} pass, {len(failed)} fail")


def render_results_tex(payload: dict[str, Any], dgp: Any) -> str:
    summary = payload["summary"]
    diagnostics = payload["diagnostics"]
    metrics = payload["metrics"]
    gates = payload["gates"]
    simulation = payload["simulation"]
    metadata = summary.metadata

    names = list(summary.parameter_names)
    estimates = np.asarray(summary.parameters, dtype=float)
    standard_errors = np.asarray(summary.standard_errors, dtype=float)
    truth = np.asarray(dgp.homogeneous_parameters, dtype=float)
    errors = estimates - truth
    failed_gates = [gate for gate in gates if not gate.passed]
    passed_gates = len(gates) - len(failed_gates)

    lines: list[str] = []
    add = lines.append

    add("% Auto-generated by nnes_run.py. Do not edit by hand.")
    add(f"% Known-truth DGP cell: {payload['cell'].cell_id}")
    add("")
    add(r"\section{Generated Validation Results}")
    add(
        "This section is generated by \\texttt{nnes\\_run.py} from the "
        "\\texttt{experiments.known\\_truth} harness and the canonical "
        "known-truth DGP. Hard gates are enforced."
    )
    add("")

    add(r"\subsection{Pre-Estimation Checks}")
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Pre-estimation checks from the known-truth NNES run.}")
    add(r"\begin{tabular}{lrl}")
    add(r"\toprule")
    add(r"Check & Value & Status \\")
    add(r"\midrule")
    add(
        f"Feature rank & {diagnostics.feature_rank} / "
        f"{diagnostics.num_features} & {status(not diagnostics.errors)} \\\\"
    )
    add(f"Feature condition number & {fmt(diagnostics.condition_number, 3)} & pass \\\\")
    add(
        "Transition row error & "
        f"${sci(diagnostics.max_transition_row_error)}$ & pass \\\\"
    )
    add(
        f"Observed states & {diagnostics.observed_states} / "
        f"{diagnostics.num_states} & pass \\\\"
    )
    add(
        f"State-action coverage & {fmt(diagnostics.state_action_coverage, 3)} "
        "& pass \\\\"
    )
    shares = ", ".join(fmt(value, 3) for value in diagnostics.action_shares)
    add(f"Action shares & {shares} & pass \\\\")
    add(f"Minimum action share & {fmt(diagnostics.min_action_share, 3)} & pass \\\\")
    add(f"Exit/absorbing anchor & {tf(diagnostics.anchor_valid)} & pass \\\\")
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")

    add(r"\subsection{Estimator Fit}")
    add(
        "The validation run uses "
        f"{int(simulation.n_individuals):,} individuals, "
        f"{int(simulation.n_periods):,} periods per individual, and "
        f"{int(summary.num_observations):,} observations."
    )
    add("")
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Known-truth NNES run summary.}")
    add(r"\begin{tabular}{lr}")
    add(r"\toprule")
    add(r"Quantity & Value \\")
    add(r"\midrule")
    add(f"Optimizer convergence flag & {tf(summary.converged)} \\\\")
    add(f"L-BFGS-B iterations & {int(summary.num_iterations)} \\\\")
    add(f"Log-likelihood & {fmt(summary.log_likelihood, 4)} \\\\")
    add(f"Estimation time & {fmt(summary.estimation_time, 2)} seconds \\\\")
    add(f"NPL outer iterations & {int(metadata['n_outer_iterations'])} \\\\")
    add(f"Final V-network loss & {fmt(metadata['v_loss_per_outer'][-1], 6)} \\\\")
    add(f"Hard gates passed & {passed_gates} / {len(gates)} \\\\")
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")

    add(
        "The profiled NPL objective recovers the structural reward, policy, "
        "Bellman-level value function, Q function, and counterfactual policies "
        "within the hard known-truth tolerances."
    )
    add("")

    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Parameter recovery.}")
    add(r"\begin{tabular}{lrrrr}")
    add(r"\toprule")
    add(r"Parameter & Truth & Estimate & SE & Error \\")
    add(r"\midrule")
    for name, true_value, estimate, se, error in zip(
        names, truth, estimates, standard_errors, errors, strict=True
    ):
        add(
            f"{tt(name)} & {fmt(true_value, 6)} & {fmt(estimate, 6)} & "
            f"{fmt(se, 6)} & {fmt(error, 6)} \\\\"
        )
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")

    parameter_metrics = metrics["parameters"]
    policy_metrics = metrics["policy"]
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Recovery metrics.}")
    add(r"\begin{tabular}{lr}")
    add(r"\toprule")
    add(r"Metric & Value \\")
    add(r"\midrule")
    add(f"Parameter RMSE & {fmt(parameter_metrics.rmse, 6)} \\\\")
    add(f"Parameter relative RMSE & {fmt(parameter_metrics.relative_rmse, 6)} \\\\")
    add(
        "Parameter cosine similarity & "
        f"{fmt(parameter_metrics.cosine_similarity, 6)} \\\\"
    )
    add(f"Reward RMSE & {fmt(metrics['reward_rmse'], 6)} \\\\")
    add(f"Value RMSE & {fmt(metrics['value_rmse'], 6)} \\\\")
    add(f"Q RMSE & {fmt(metrics['q_rmse'], 6)} \\\\")
    add(f"Policy KL & ${sci(policy_metrics.kl)}$ \\\\")
    add(f"Policy total variation & {fmt(policy_metrics.tv, 6)} \\\\")
    add(f"Policy max state L1 & {fmt(policy_metrics.linf, 6)} \\\\")
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")

    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Hard recovery gates.}")
    add(r"\begin{tabular}{llrl}")
    add(r"\toprule")
    add(r"Gate & Threshold & Value & Status \\")
    add(r"\midrule")
    for gate in gates:
        add(
            f"{tex_text(gate.name)} & {gate_threshold(gate)} & "
            f"{gate_value(gate.value)} & {status(gate.passed)} \\\\"
        )
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")
    add("")

    add(r"\subsection{Counterfactual Recovery}")
    add(r"\begin{table}[H]")
    add(r"\centering\small")
    add(r"\caption{Counterfactual recovery against known oracle objects.}")
    add(r"\begin{tabular}{lrrrr}")
    add(r"\toprule")
    add(r"Counterfactual & Policy TV & Policy KL & Value RMSE & Regret \\")
    add(r"\midrule")
    for kind, label in (
        ("type_a", "Type A"),
        ("type_b", "Type B"),
        ("type_c", "Type C"),
    ):
        cf = metrics["counterfactuals"][kind]
        add(
            f"{label} & {fmt(cf.policy.tv, 6)} & ${sci(cf.policy.kl)}$ & "
            f"{fmt(cf.value_rmse, 6)} & {fmt(cf.regret, 6)} \\\\"
        )
    add(r"\bottomrule")
    add(r"\end{tabular}")
    add(r"\end{table}")

    return "\n".join(lines) + "\n"


def compact_payload(payload: dict[str, Any]) -> dict[str, Any]:
    summary = payload["summary"]
    metadata = summary.metadata
    return {
        "cell_id": payload["cell"].cell_id,
        "estimator": payload["estimator"],
        "simulation": payload["simulation"],
        "compatibility": payload["compatibility"],
        "diagnostics": payload["diagnostics"],
        "summary": {
            "parameter_names": summary.parameter_names,
            "parameters": summary.parameters,
            "standard_errors": finite_list(summary.standard_errors),
            "log_likelihood": summary.log_likelihood,
            "converged": summary.converged,
            "num_iterations": summary.num_iterations,
            "num_observations": summary.num_observations,
            "estimation_time": summary.estimation_time,
            "convergence_message": summary.convergence_message,
            "metadata": {
                "profile_mode": metadata.get("profile_mode"),
                "n_outer_iterations": metadata.get("n_outer_iterations"),
                "v_loss_per_outer": metadata.get("v_loss_per_outer"),
            },
        },
        "metrics": payload["metrics"],
        "gates": payload["gates"],
    }


def fmt(value: float | None, digits: int = 4) -> str:
    if value is None:
        return "---"
    number = float(value)
    if not math.isfinite(number):
        return "---"
    return f"{number:.{digits}f}"


def finite_list(values: Any) -> list[float | None]:
    array = np.asarray(values, dtype=float)
    return [float(value) if math.isfinite(float(value)) else None for value in array]


def sci(value: float) -> str:
    number = float(value)
    if not math.isfinite(number):
        return "---"
    mantissa, exponent = f"{number:.2e}".split("e")
    return rf"{mantissa}\times 10^{{{int(exponent)}}}"


def tf(value: bool) -> str:
    return "true" if bool(value) else "false"


def status(passed: bool) -> str:
    return "pass" if bool(passed) else "fail"


def tt(value: str) -> str:
    return r"\texttt{" + tex_text(value) + "}"


def tex_text(value: str) -> str:
    return (
        str(value)
        .replace("\\", r"\textbackslash{}")
        .replace("_", r"\_")
        .replace("%", r"\%")
        .replace("&", r"\&")
        .replace("#", r"\#")
    )


def gate_threshold(gate: Any) -> str:
    if gate.operator == "is":
        return tf(gate.threshold)
    operator = r"$\leq$" if gate.operator == "<=" else r"$\geq$"
    return f"{operator} {gate_value(gate.threshold)}"


def gate_value(value: Any) -> str:
    if isinstance(value, bool):
        return tf(value)
    if isinstance(value, (int, float)):
        return fmt(value, 6)
    return tex_text(str(value))


if __name__ == "__main__":
    main()
