"""Simulation and counterfactual analysis."""

from econirl.simulation.synthetic import simulate_panel
from econirl.simulation.counterfactual import (
    CounterfactualType,
    CounterfactualResult,
    counterfactual,
    counterfactual_policy,
    counterfactual_transitions,
    compute_stationary_distribution,
    compute_welfare_effect,
    demand_function,
    discount_factor_change,
    elasticity_analysis,
    neural_choice_set_counterfactual,
    neural_global_perturbation,
    neural_local_perturbation,
    neural_perturbation_sweep,
    neural_policy_jacobian,
    neural_reward_counterfactual,
    neural_sieve_compression,
    neural_transition_counterfactual,
    simulate_counterfactual,
    state_extrapolation,
    welfare_decomposition,
)

__all__ = [
    "CounterfactualType",
    "CounterfactualResult",
    "counterfactual",
    "counterfactual_policy",
    "counterfactual_transitions",
    "compute_stationary_distribution",
    "compute_welfare_effect",
    "demand_function",
    "discount_factor_change",
    "elasticity_analysis",
    "neural_choice_set_counterfactual",
    "neural_global_perturbation",
    "neural_local_perturbation",
    "neural_perturbation_sweep",
    "neural_policy_jacobian",
    "neural_reward_counterfactual",
    "neural_sieve_compression",
    "neural_transition_counterfactual",
    "simulate_counterfactual",
    "simulate_panel",
    "state_extrapolation",
    "welfare_decomposition",
]
