#!/usr/bin/env python3
"""SEES Primer — auto-generate results for the LaTeX document.

Runs SEES (Fourier basis, K=8) and NFXP (oracle) on a simulated panel
from the Rust (1987) bus replacement model. Writes LaTeX macros and a
results table to sees_results.tex.

This script reproduces a scaled-up variant of Rust's bus engine to
demonstrate SEES's computational advantage: the sieve basis avoids the
inner fixed-point loop entirely, making SEES faster than NFXP even on
moderate state spaces while achieving comparable log-likelihood.

Usage:
    cd /path/to/econirl
    python papers/econirl_package/primers/sees/sees_run.py
"""

import json
import time
from pathlib import Path

import jax.numpy as jnp
import numpy as np

OUT = Path(__file__).resolve().parent / "sees_results.tex"

# ---------- DGP settings (Rust 1987) ----------
TRUE_OC = 0.001          # operating cost per mileage bin
TRUE_RC = 3.0            # replacement cost
N_STATES = 200           # mileage bins (large to show SEES scaling)
DISCOUNT = 0.9999        # beta
N_BUSES = 200            # number of individuals
N_PERIODS = 100          # periods per bus
SEED = 42


def main():
    from econirl.environments.rust_bus import RustBusEnvironment
    from econirl.estimation.nfxp import NFXPEstimator
    from econirl.estimation.sees import SEESConfig, SEESEstimator
    from econirl.preferences.linear import LinearUtility
    from econirl.simulation.synthetic import simulate_panel

    n_obs = N_BUSES * N_PERIODS

    print("SEES Primer — generating results")
    print(f"  Environment: Rust bus, {N_STATES} bins, beta={DISCOUNT}")
    print(f"  Data: {N_BUSES} x {N_PERIODS} = {n_obs:,} obs")

    env = RustBusEnvironment(
        operating_cost=TRUE_OC,
        replacement_cost=TRUE_RC,
        num_mileage_bins=N_STATES,
        discount_factor=DISCOUNT,
        seed=SEED,
    )
    problem = env.problem_spec
    transitions = env.transition_matrices
    utility = LinearUtility.from_environment(env)

    panel = simulate_panel(
        env, n_individuals=N_BUSES, n_periods=N_PERIODS,
        seed=SEED + 1000,
    )

    results = {}

    # ── NFXP oracle ──
    print("\n  Running NFXP...")
    nfxp = NFXPEstimator(
        inner_solver="hybrid",
        inner_tol=1e-12,
        inner_max_iter=300000,
        switch_tol=1e-3,
        outer_max_iter=200,
        compute_hessian=True,
        verbose=False,
    )
    t0 = time.time()
    nfxp_res = nfxp.estimate(panel, utility, problem, transitions)
    nfxp_time = time.time() - t0
    nfxp_params = np.asarray(nfxp_res.parameters)
    nfxp_se = np.asarray(nfxp_res.standard_errors)

    results["nfxp"] = {
        "theta_c": float(nfxp_params[0]),
        "RC": float(nfxp_params[1]),
        "se_theta_c": float(nfxp_se[0]),
        "se_RC": float(nfxp_se[1]),
        "ll": float(nfxp_res.log_likelihood),
        "time": nfxp_time,
    }
    print(f"    theta_c={nfxp_params[0]:.6f} (SE {nfxp_se[0]:.6f}), "
          f"RC={nfxp_params[1]:.4f} (SE {nfxp_se[1]:.4f}), "
          f"LL={nfxp_res.log_likelihood:.1f}, time={nfxp_time:.1f}s")

    # ── SEES (Fourier basis) ──
    print("\n  Running SEES...")
    sees_cfg = SEESConfig(
        basis_type="fourier",
        basis_dim=8,
        penalty_weight=10.0,
        max_iter=500,
        compute_se=True,
        se_method="asymptotic",
        verbose=False,
    )
    sees_est = SEESEstimator(config=sees_cfg)

    t0 = time.time()
    sees_res = sees_est.estimate(panel, utility, problem, transitions)
    sees_time = time.time() - t0
    sees_params = np.asarray(sees_res.parameters)
    sees_se = np.asarray(sees_res.standard_errors)

    bellman_viol = 0.0
    if sees_res.metadata and "bellman_violation" in sees_res.metadata:
        bellman_viol = float(sees_res.metadata["bellman_violation"])

    results["sees"] = {
        "theta_c": float(sees_params[0]),
        "RC": float(sees_params[1]),
        "se_theta_c": float(sees_se[0]),
        "se_RC": float(sees_se[1]),
        "ll": float(sees_res.log_likelihood),
        "time": sees_time,
        "bellman_violation": bellman_viol,
    }
    print(f"    theta_c={sees_params[0]:.6f} (SE {sees_se[0]:.6f}), "
          f"RC={sees_params[1]:.4f} (SE {sees_se[1]:.4f}), "
          f"LL={sees_res.log_likelihood:.1f}, time={sees_time:.1f}s")

    speedup = nfxp_time / sees_time if sees_time > 0 else float("inf")
    ll_gap = abs(float(sees_res.log_likelihood) - float(nfxp_res.log_likelihood))
    print(f"\n  Speedup: {speedup:.1f}x")
    print(f"  LL gap: {ll_gap:.2f}")

    # ── Write LaTeX ──
    tex = []
    tex.append("% Auto-generated by sees_run.py — do not edit by hand")
    tex.append(f"% Rust bus {N_STATES} bins, beta={DISCOUNT}, {n_obs} obs, seed={SEED}")
    tex.append("")
    tex.append(f"\\newcommand{{\\seesNstates}}{{{N_STATES}}}")
    tex.append(f"\\newcommand{{\\seesBeta}}{{{DISCOUNT}}}")
    tex.append(f"\\newcommand{{\\seesNobs}}{{{n_obs:,}}}")
    tex.append(f"\\newcommand{{\\seesTrueOC}}{{{TRUE_OC}}}")
    tex.append(f"\\newcommand{{\\seesTrueRC}}{{{TRUE_RC}}}")
    tex.append("")
    # NFXP
    tex.append(f"\\newcommand{{\\seesNfxpOC}}{{{float(nfxp_params[0]):.6f}}}")
    tex.append(f"\\newcommand{{\\seesNfxpRC}}{{{float(nfxp_params[1]):.4f}}}")
    tex.append(f"\\newcommand{{\\seesNfxpSEOC}}{{{float(nfxp_se[0]):.6f}}}")
    tex.append(f"\\newcommand{{\\seesNfxpSERC}}{{{float(nfxp_se[1]):.4f}}}")
    tex.append(f"\\newcommand{{\\seesNfxpLL}}{{{float(nfxp_res.log_likelihood):.1f}}}")
    tex.append(f"\\newcommand{{\\seesNfxpTime}}{{{nfxp_time:.1f}}}")
    tex.append("")
    # SEES
    tex.append(f"\\newcommand{{\\seesOC}}{{{float(sees_params[0]):.6f}}}")
    tex.append(f"\\newcommand{{\\seesRC}}{{{float(sees_params[1]):.4f}}}")
    tex.append(f"\\newcommand{{\\seesSEOC}}{{{float(sees_se[0]):.6f}}}")
    tex.append(f"\\newcommand{{\\seesSERC}}{{{float(sees_se[1]):.4f}}}")
    tex.append(f"\\newcommand{{\\seesLL}}{{{float(sees_res.log_likelihood):.1f}}}")
    tex.append(f"\\newcommand{{\\seesTime}}{{{sees_time:.1f}}}")
    tex.append(f"\\newcommand{{\\seesSpeedup}}{{{speedup:.1f}}}")
    tex.append(f"\\newcommand{{\\seesLLgap}}{{{ll_gap:.2f}}}")
    tex.append(f"\\newcommand{{\\seesBellmanViol}}{{{bellman_viol:.2e}}}")
    tex.append("")

    # Embedded results table
    tex.append("\\begin{table}[h!]")
    tex.append("\\centering\\small")
    tex.append(f"\\caption{{Rust bus engine (\\seesNstates\\ bins, "
               f"$\\beta=\\seesBeta$, \\seesNobs\\ obs). "
               f"SEES uses a Fourier basis with $K=8$ terms.}}")
    tex.append("\\label{tab:sees_results}")
    tex.append("\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}} l r r r}")
    tex.append("\\toprule")
    tex.append("& True & NFXP & SEES \\\\")
    tex.append("\\midrule")
    tex.append("$\\hat\\theta_c$ & \\seesTrueOC & \\seesNfxpOC & \\seesOC \\\\")
    tex.append("SE($\\hat\\theta_c$) & --- & \\seesNfxpSEOC & \\seesSEOC \\\\")
    tex.append("$\\widehat{RC}$ & \\seesTrueRC & \\seesNfxpRC & \\seesRC \\\\")
    tex.append("SE($\\widehat{RC}$) & --- & \\seesNfxpSERC & \\seesSERC \\\\")
    tex.append("Log-likelihood & --- & $\\seesNfxpLL$ & $\\seesLL$ \\\\")
    tex.append("Time (s) & --- & \\seesNfxpTime & \\seesTime \\\\")
    tex.append("\\bottomrule")
    tex.append("\\end{tabular*}")
    tex.append("\\end{table}")

    OUT.write_text("\n".join(tex) + "\n")
    print(f"\n  Wrote {OUT}")
    OUT.with_suffix(".json").write_text(json.dumps(results, indent=2, default=float))
    print(f"  Wrote {OUT.with_suffix('.json')}")


if __name__ == "__main__":
    main()
