#!/usr/bin/env python3
"""SEES Primer — auto-generate results for the LaTeX document.

Demonstrates SEES's core advantage: on a large state space (K=2
multi-component bus, 400 states), SEES matches NFXP's log-likelihood
while running an order of magnitude faster. NFXP must solve a 400x400
Bellman fixed point at each parameter guess; SEES approximates V(s)
with 8 Fourier terms and optimizes in one L-BFGS-B call.

This replicates the computational scaling argument from Luo and Sang
(2024, Section 2): SEES cost is O(K) independent of |S|.

Usage:
    python papers/econirl_package/primers/sees/sees_run.py
"""

import json
import time
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parent / "sees_results.tex"

# ---------- DGP: Multi-component bus (large state space) ----------
K_COMPONENTS = 2         # number of independent bus components
M_BINS = 30             # mileage bins per component → 900 total states
DISCOUNT = 0.9999
SEED = 42
N_BUSES = 100
N_PERIODS = 100


def main():
    from econirl.environments.multi_component_bus import MultiComponentBusEnvironment
    from econirl.estimation.nfxp import NFXPEstimator
    from econirl.estimation.sees import SEESConfig, SEESEstimator
    from econirl.preferences.linear import LinearUtility
    from econirl.simulation.synthetic import simulate_panel

    env = MultiComponentBusEnvironment(
        K=K_COMPONENTS, M=M_BINS, discount_factor=DISCOUNT,
    )
    n_states = env.num_states
    n_obs = N_BUSES * N_PERIODS
    true_params = env.get_true_parameter_vector()
    problem = env.problem_spec
    transitions = env.transition_matrices
    utility = LinearUtility.from_environment(env)

    print("SEES Primer — generating results")
    print(f"  Environment: {K_COMPONENTS}-component bus, {M_BINS} bins/component, "
          f"{n_states} total states, beta={DISCOUNT}")
    print(f"  Data: {N_BUSES} x {N_PERIODS} = {n_obs:,} obs")
    print(f"  True params: {dict(zip(env.parameter_names, np.asarray(true_params)))}")

    panel = simulate_panel(
        env, n_individuals=N_BUSES, n_periods=N_PERIODS, seed=SEED,
    )

    results = {}

    # ── NFXP oracle ──
    print("\n  Running NFXP...")
    nfxp = NFXPEstimator(
        inner_solver="hybrid", inner_tol=1e-10, inner_max_iter=100000,
        switch_tol=1e-3, outer_max_iter=200,
        compute_hessian=True, verbose=False,
    )
    t0 = time.time()
    nfxp_res = nfxp.estimate(panel, utility, problem, transitions)
    nfxp_time = time.time() - t0
    nfxp_p = np.asarray(nfxp_res.parameters)
    nfxp_se = np.asarray(nfxp_res.standard_errors)
    results["nfxp"] = {
        "params": [float(x) for x in nfxp_p],
        "se": [float(x) for x in nfxp_se],
        "ll": float(nfxp_res.log_likelihood),
        "time": nfxp_time,
    }
    print(f"    params={[f'{x:.4f}' for x in nfxp_p]}, "
          f"LL={nfxp_res.log_likelihood:.1f}, time={nfxp_time:.1f}s")

    # ── SEES ──
    print("\n  Running SEES (Fourier K=8)...")
    sees_cfg = SEESConfig(
        basis_type="fourier", basis_dim=8, penalty_weight=10.0,
        max_iter=500, compute_se=True, se_method="asymptotic", verbose=False,
    )
    sees_est = SEESEstimator(config=sees_cfg)
    t0 = time.time()
    sees_res = sees_est.estimate(panel, utility, problem, transitions)
    sees_time = time.time() - t0
    sees_p = np.asarray(sees_res.parameters)
    sees_se = np.asarray(sees_res.standard_errors)
    results["sees"] = {
        "params": [float(x) for x in sees_p],
        "se": [float(x) for x in sees_se],
        "ll": float(sees_res.log_likelihood),
        "time": sees_time,
    }
    print(f"    params={[f'{x:.4f}' for x in sees_p]}, "
          f"LL={sees_res.log_likelihood:.1f}, time={sees_time:.1f}s")

    speedup = nfxp_time / sees_time if sees_time > 0 else float("inf")
    ll_gap = abs(float(sees_res.log_likelihood) - float(nfxp_res.log_likelihood))
    print(f"\n  Speedup: {speedup:.1f}x, LL gap: {ll_gap:.2f}")

    # ── Write LaTeX macros + table ──
    pnames = env.parameter_names
    tex = []
    tex.append("% Auto-generated by sees_run.py — do not edit by hand")
    tex.append(f"% {K_COMPONENTS}-component bus, {M_BINS} bins/comp, "
               f"{n_states} states, {n_obs} obs, seed={SEED}")
    tex.append("")
    tex.append(f"\\newcommand{{\\seesNstates}}{{{n_states}}}")
    tex.append(f"\\newcommand{{\\seesBeta}}{{{DISCOUNT}}}")
    tex.append(f"\\newcommand{{\\seesNobs}}{{{n_obs:,}}}")
    tex.append(f"\\newcommand{{\\seesKcomp}}{{{K_COMPONENTS}}}")
    tex.append(f"\\newcommand{{\\seesMbins}}{{{M_BINS}}}")
    tex.append(f"\\newcommand{{\\seesSpeedup}}{{{speedup:.0f}}}")
    tex.append(f"\\newcommand{{\\seesLLgap}}{{{ll_gap:.2f}}}")
    tex.append(f"\\newcommand{{\\seesNfxpTime}}{{{nfxp_time:.1f}}}")
    tex.append(f"\\newcommand{{\\seesTime}}{{{sees_time:.1f}}}")
    tex.append("")

    # Results table
    tex.append("\\begin{table}[h!]")
    tex.append("\\centering\\small")
    tex.append(f"\\caption{{\\seesKcomp-component bus engine "
               f"(\\seesNstates\\ states, $\\beta=\\seesBeta$, \\seesNobs\\ obs). "
               f"SEES uses a Fourier basis with $K=8$.}}")
    tex.append("\\label{tab:sees_results}")
    tex.append("\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}} l r r r}")
    tex.append("\\toprule")
    tex.append("& True & NFXP & SEES \\\\")
    tex.append("\\midrule")
    for i, name in enumerate(pnames):
        true_val = float(true_params[i])
        nfxp_val = float(nfxp_p[i])
        sees_val = float(sees_p[i])
        nfxp_se_val = float(nfxp_se[i])
        sees_se_val = float(sees_se[i])
        tex.append(f"${name}$ & {true_val:.4f} & {nfxp_val:.4f} & {sees_val:.4f} \\\\")
        se_nfxp = f"{nfxp_se_val:.4f}" if not np.isnan(nfxp_se_val) else "---"
        se_sees = f"{sees_se_val:.4f}" if not np.isnan(sees_se_val) else "---"
        tex.append(f"\\quad SE & --- & {se_nfxp} & {se_sees} \\\\")
    tex.append(f"Log-lik & --- & ${float(nfxp_res.log_likelihood):.1f}$ "
               f"& ${float(sees_res.log_likelihood):.1f}$ \\\\")
    tex.append(f"Time (s) & --- & {nfxp_time:.1f} & {sees_time:.1f} \\\\")
    tex.append("\\bottomrule")
    tex.append("\\end{tabular*}")
    tex.append("\\end{table}")

    OUT.write_text("\n".join(tex) + "\n")
    print(f"\n  Wrote {OUT}")
    OUT.with_suffix(".json").write_text(json.dumps(results, indent=2))
    print(f"  Wrote {OUT.with_suffix('.json')}")


if __name__ == "__main__":
    main()
